/* ============================================================================
   WEMBA 52 SF · 코호트 생존 대시보드 데이터
   ----------------------------------------------------------------------------
   Term 2 (Fall 2026) · 구성 개편판 · 2026-08-23
   · 섹션 순서 = 지금 준비 → 다가오는 일정 → 수업 일정표 → 과목 → Block Week → 자료 맵 → 디너
   · What's New 는 메인에서 빼고 '업데이트 내역'(changelog)에만 둡니다
   · 모든 시각은 PT 기준. Canvas 가 ET·UTC 로 보여주는 값은 PT 로 환산해 적었습니다
   · 3언어 필수: kr / en / cn  (하나라도 빠지면 그 언어에서 빈칸)
   · 수정할 때 meta.lastUpdated 를 반드시 함께 바꾸세요
   ========================================================================== */

const DATA = {

  meta: {
    cohort: "WEMBA 52",
    lastUpdated:"2026-09-11",
    author:   "Sally",
    tzLabel:  "PT",
    cheerOverride: { date:"", sub:{ kr:"", en:"", cn:"" } },
  },

  /* ── 학기 시작 축하 배너 ──────────────────────────────────────────
     until 날짜가 지나면 자동으로 사라집니다. 다 쓰면 kickoff 를 지우세요. */

  /* ── 임시 안내 카드 ────────────────────────────────────────────────
     until 날짜가 지나면 자동으로 사라집니다. 다 쓰면 notice 를 지우세요. */

  /* ── 지금 준비가 필요한 것 (최상단 요약 카드) ─────────────────────── */
  prep: {
    window: { kr:"지금 ~ 9/11–12 수업 주말", en:"Now through the Sep 11–12 class weekend", cn:"现在 ~ 9/11–12 上课周末" },
    note: {
      kr:"**FNCE Quiz #1 은 9/10 자정으로 마감**됐습니다. ⚠️ **이번 주말(9/11–12)에는 LGST 수업이 없습니다** — 리딩 8건은 9/25–26 용이니 다음 구간에 다시 올리겠습니다. 아래는 **이번 주말 두 세션에서 실제로 진행되는 것**입니다.",
      en:"**FNCE Quiz #1 closed at midnight on Sep 10.** ⚠️ **There is no LGST this weekend (Sep 11–12)** — the eight readings are for Sep 25–26 and will come back here then. Below is **what actually happens in the two sessions this weekend**.",
      cn:"**FNCE Quiz #1 已于 9/10 午夜截止。** ⚠️ **本周末(9/11–12)无 LGST 课** — 8篇阅读用于 9/25–26,届时会再列出。以下是**本周末两节课实际进行的内容**。" },
    cards: [
      {
        course:"9/11(금)", color:"#8e8a99", flag:true,
        when:{ kr:"금 9/11 · STAT 첫 수업 + FNCE", en:"Fri Sep 11 · first STAT class + FNCE", cn:"周五 9/11 · STAT 首堂课 + FNCE" },
        badge:{ kr:"면제시험 + 리딩", en:"Waiver exam + readings", cn:"免修考试 + 阅读" },
        lines:[
          { icon:"📝", text:{ kr:"**STAT 6130 면제 시험** — 첫 수업 시간에 진행 · **응시하려면 사전에 Craig 과 조율이 필요**합니다",
                              en:"**STAT 6130 waiver exam** — during the first class · **you must coordinate with Craig in advance to sit it**",
                              cn:"**STAT 6130 免修考试** — 首堂课时间进行 · **应试须事先与 Craig 协调**" },
                     sub:{ kr:"금요일이 유일한 시행 기회입니다 · 섹션 1 은 오후 세션에 진행 · 불합격해도 불이익 없습니다",
                            en:"Friday is the only time it is offered · Section 1 sits it in the afternoon session · no penalty for not passing",
                            cn:"周五是唯一的考试机会 · 第1班在下午场进行 · 未通过无不利影响" } },
          { icon:"📖", text:{ kr:"**FNCE 노동시장** — ABC Ch.3.2–3.6 · Jones Ch.7", en:"**FNCE labor market** — ABC Ch. 3.2–3.6, Jones Ch. 7", cn:"**FNCE 劳动力市场** — ABC Ch.3.2–3.6 · Jones Ch.7" } },
          { icon:"📖", text:{ kr:"**FNCE 소비·저축** — ABC Ch.4.1(부록 4.A 포함) · Jones Ch.16",
                              en:"**FNCE consumption and saving** — ABC Ch. 4.1 including Appendix 4.A, Jones Ch. 16",
                              cn:"**FNCE 消费与储蓄** — ABC Ch.4.1(含附录4.A)· Jones Ch.16" },
                     sub:{ kr:"교수가 **\"an important block\"** 이라고 못 박은 대목입니다", en:"The professor called this **\"an important block\"**", cn:"教授明确称此为 **\"an important block\"**" } },
        ],
      },
      {
        course:"9/12(토)", color:"#7ba05b",
        when:{ kr:"토 9/12 · 마지막 1시간", en:"Sat Sep 12 · the last hour", cn:"周六 9/12 · 最后一小时" },
        badge:{ kr:"연습 미드텀", en:"Practice midterm", cn:"模拟期中" },
        lines:[
          { icon:"⭐", text:{ kr:"**리뷰 세션에서 Practice Midterm 을 배포하고 함께 풀이**합니다",
                              en:"**A practice midterm is handed out and worked through** in the review session",
                              cn:"**复习课将发放并讲解模拟期中**" },
                     sub:{ kr:"수업 몇 시간 전에 Canvas 에 먼저 올라올 수 있습니다", en:"It may go up on Canvas a few hours before class", cn:"可能于课前数小时先上传 Canvas" } },
          { icon:"📖", text:{ kr:"**투자와 재화시장 균형** — 이 세션 범위", en:"**Investment and goods market equilibrium** — this session", cn:"**投资与商品市场均衡** — 本节范围" } },
          { icon:"📝", text:{ kr:"**주말 안에 조원과 LGST 발표 주제를 정해 두세요** — 제출은 **9/16(수) 17:00 PT**",
                              en:"**Settle your LGST presentation topic with your group before the weekend ends** — it is due **Wed Sep 16, 5 PM PT**",
                              cn:"**请在周末结束前与组员敲定 LGST 展示主题** — 提交截止 **9/16(周三)17:00 PT**" },
                     sub:{ kr:"조 대표 1명이 후보 2~3개를 각 한 문장 + 선호 순위로 교수에게 메일 · **다음 LGST 수업은 9/25 라 이번 주말이 유일한 대면 기회**입니다",
                            en:"One representative emails 2 to 3 ranked ideas, one sentence each · **the next LGST class is Sep 25, so this weekend is the only in-person window**",
                            cn:"由一名组代表将2~3个候选(各一句话并排序)邮件给教授 · **下次 LGST 课为 9/25,本周末是唯一的面对面机会**" } },
        ],
      },
    ],
  },
  changelog: [
  {
    date:"2026-09-11",
    items:[
      { kr:"🌐 **영어·중국어로 보면 한국어가 섞여 나오던 문제를 고쳤습니다** — 블록위크 상태줄 9개, 시간표의 `종일`·`예약제`, Canvas 맵의 `Course Match` 항목이 번역 없이 한국어로만 나오고 있었습니다. 12곳을 3개 언어로 채웠습니다",
        en:"🌐 **Fixed Korean text leaking into the English and Chinese views** — nine block-week status lines, the `All day` and `By appt.` rows in the schedule, and the `Course Match` row in the Canvas map were rendering in Korean only. All twelve now carry all three languages",
        cn:"🌐 **修复了英文与中文视图中混入韩文的问题** — Block Week 状态行9处、课表中的`全天`·`预约制`、Canvas 地图中的 `Course Match` 此前仅显示韩文。12处均已补齐三种语言" },
      { kr:"📌 **「지금 준비가 필요한 것」을 이번 주말 두 세션 기준으로 정리했습니다** — 마감된 FNCE Quiz #1 카드는 내렸고, **STAT 면제시험은 Craig 사전 조율이 필요**하다는 점을 넣었습니다. ⚠️ **LGST 리딩 8건은 9/25–26 용**이라 그 구간이 되면 다시 올리겠습니다",
        en:"📌 **Rebuilt \"Prepare before class\" around this weekend's two sessions** — the closed FNCE Quiz #1 card is gone, and the **STAT waiver exam now notes that you must coordinate with Craig first**. ⚠️ **The eight LGST readings are for Sep 25–26** and will return here for that window",
        cn:"📌 **「现在需要准备的」已按本周末两节课重新整理** — 已下架截止的 FNCE Quiz #1,并补充**STAT 免修考试须事先与 Craig 协调**。⚠️ **LGST 的8篇阅读用于 9/25–26**,届时会再次列出" },
      { kr:"🔢 **LGST 6420(Accountable AI) 대기 인원 표기 정정** — 언어에 따라 41명/42명으로 갈려 있어 **42명**으로 통일했습니다",
        en:"🔢 **Corrected the LGST 6420 (Accountable AI) waitlist figure** — it read 41 in some languages and 42 in others; it is now **42** everywhere",
        cn:"🔢 **修正 LGST 6420(Accountable AI)候补人数** — 各语言版本此前为41/42不一,现统一为 **42人**" },
    ],
  },
  {
    date:"2026-09-03",
    items:[
      { kr:"🔴 **LGST 조별 발표 지침이 배포됐습니다 — 발표는 10/9–10/10.** Feinstein 교수가 9/3 메일로 `Group Project Instructions Fall 26.docx` 를 보냈습니다. **Canvas 과제 목록에는 아직 없으니** 메일을 따로 보관해 두세요. 10/8 FNCE 중간고사·STAT Quiz 2 와 같은 주라 **10월 둘째 주가 최대 고비**입니다",
        en:"🔴 **LGST group presentation instructions are out — presentations are Oct 9–10.** Prof. Feinstein emailed `Group Project Instructions Fall 26.docx` on Sep 3. **It is not on the Canvas assignment list yet**, so keep the email. It shares a week with the FNCE midterm and STAT Quiz 2 on Oct 8, making **the second week of October the crunch**",
        cn:"🔴 **LGST 小组展示指引已发布 — 展示为 10/9–10/10。** Feinstein 教授于 9/3 邮件发送 `Group Project Instructions Fall 26.docx`。**Canvas 作业列表中尚无**,请保存邮件。与 10/8 的 FNCE 期中、STAT Quiz 2 同周,**十月第二周为最大关口**" },
      { kr:"🔴 **Winter GMC 지원이 9/14 에 마감됩니다.** 포털은 `wharton-sa.terradotta.com` 이고, ⭐ **좌측 필터 「Open to」에서 `WEMBA28` + `WEMBAW28` 를 선택해야** 지원 가능한 과정이 보입니다. **우리 코호트는 Vietnam** 이 열려 있고 **Brazil·Finance in UAE 는 1/15 수업과 겹쳐 막혀 있습니다.** 미국 내 과정은 없습니다. 리더십 벤처(설명회 9/8·마감 9/14)도 같은 포털·같은 필터이며 **GMC 와는 별개 트랙**입니다 (Antarctica Trekking 등). ⭐ **여러 곳에 동시 지원해 두고 합격 후 고르는 방식이 가능**합니다",
        en:"🔴 **Winter GMC applications close Sep 14.** The portal is `wharton-sa.terradotta.com`, and ⭐ **you must select `WEMBA28` and `WEMBAW28` under \"Open to\" in the left filter** to see what you can apply to. **Vietnam is open to our cohort**; **Brazil and Finance in UAE are blocked by the Jan 15 class.** There are no US based options. Leadership Ventures (info session Sep 8, deadline Sep 14) use the same portal and filters and are a **separate track** (Antarctica Trekking and others). ⭐ **You can apply to several and pick after the acceptances**",
        cn:"🔴 **冬季 GMC 报名 9/14 截止。** 入口为 `wharton-sa.terradotta.com`,⭐ **须在左侧筛选「Open to」中选择 `WEMBA28` 与 `WEMBAW28`** 才能看到可申请课程。**本班可申请 Vietnam**;**Brazil 与 Finance in UAE 因 1/15 上课日冲突而关闭。** 无美国境内课程。领导力探险(说明会 9/8、截止 9/14)使用同一入口与筛选,且**属不同轨道**(如 Antarctica Trekking)。⭐ **可同时申请多个,录取后再择一**" },
      { kr:"📄 **미시(Econ) 최종 성적이 Path@Penn 에 게시**됐습니다 (9/3). **Canvas 가 아닙니다.** 그리고 ⚠️ **지난 학기 수업 녹화본이 전부 삭제**됐습니다 — 회계·미시 포함 전 과목입니다",
        en:"📄 **Final Econ grades are posted on Path@Penn** (Sep 3), **not on Canvas.** Also ⚠️ **all recordings from last term have been removed**, accounting and micro included",
        cn:"📄 **微观经济最终成绩已发布于 Path@Penn**(9/3),**并非 Canvas。** 另外 ⚠️ **上学期全部课程录像已被删除**,含会计与微观" },
    ],
  },
    { date:"2026-09-02", items:[
      { kr:"🔴 **FNCE 퀴즈 규칙 변경 — 시도 3회 · 최고점 반영 · 정오답 확인 가능.** 8/29 수업 중 교수가 발표했고 Canvas 설정도 이미 바뀌어 있습니다. **Quiz #1 은 8/30 에 이미 열렸고 9/10(목) 23:59 PT 마감**입니다. 1차를 그냥 풀어보고 오답을 확인한 뒤 2·3차를 보시면 됩니다",
        en:"🔴 **FNCE quiz rules changed — three attempts, highest score counts, and correct answers are visible.** Announced in the Aug 29 class and already reconfigured on Canvas. **Quiz #1 opened Aug 30 and is due Thu Sep 10, 11:59 PM PT.** Take attempt 1 cold, review the misses, then attempt 2 and 3",
        cn:"🔴 **FNCE 测验规则变更 — 可考3次 · 取最高分 · 可查看对错。** 教授于 8/29 课上宣布,Canvas 设置已同步更改。**Quiz #1 已于 8/30 开放,9/10(周四)23:59 PT 截止。** 建议先裸考一次,查看错题后再考第2、3次" },
      { kr:"📄 **여름 과목 채점본이 올라오는 중인데 알림이 가지 않습니다.** 과목이 past 로 내려가면서 메일이 발송되지 않으니 **Canvas ▸ All Courses ▸ Past Enrollments ▸ 과목 ▸ Grades** 에서 직접 확인하세요. 채점본은 기말 항목의 **코멘트**에 첨부돼 있습니다",
        en:"📄 **Summer course grades are being posted, but without notifications.** Once a course moves to past enrollments no email goes out, so check **Canvas ▸ All Courses ▸ Past Enrollments ▸ course ▸ Grades** yourself. The marked-up copy is attached as a **comment** on the final",
        cn:"📄 **暑期课程成绩正在公布,但不会发送通知。** 课程移至 past 后不再发邮件,请自行前往 **Canvas ▸ All Courses ▸ Past Enrollments ▸ 课程 ▸ Grades** 查看。批改稿附于期末项目的**评论**中" },
      { kr:"📋 **FNCE 시험 형식이 공개됐습니다** — **3분의 2 ~ 4분의 3이 객관식** + 짧은 서술. 방향 판단(increase/decrease/appreciate/depreciate)과 숫자 대입이 중심이고 거대 모형 풀이는 없습니다. 다만 교수가 **\"진짜 어려움은 강의들을 연결하는 데서 온다\"** 고 경고했습니다",
        en:"📋 **The FNCE exam format is known** — **two-thirds to three-quarters multiple choice** plus short essay, centred on direction calls (increase / decrease / appreciate / depreciate) and plugging in numbers, with no large model derivations. But he warned that **\"the real challenge comes from linking the lectures\"**",
        cn:"📋 **FNCE 考试形式已公布** — **三分之二至四分之三为选择题**,另有简答,重在方向判断(increase/decrease/appreciate/depreciate)与代入数字,不考大型模型推导。但教授提醒 **\"真正的挑战来自把各讲串联起来\"**" },
      { kr:"🧑‍🏫 **매크로 TA 오피스아워는 Q&A 형식입니다** (월 18–19시 · 화 20–21시 PT, Zoom). 미시 TA 처럼 보충 강의나 문제풀이를 해주지 않고 질문을 받는 자리이며, **참석자가 적으면 사실상 1:1** 입니다. 🎧 그리고 Landry 교수가 말한 팟캐스트는 **Marketplace 금요일 랩업**(10~15분)입니다",
        en:"🧑‍🏫 **The macro TA sessions are Q&A** (Mon 6–7 PM, Tue 8–9 PM PT, Zoom). Unlike the micro TA there is no supplementary lecture or problem set walk-through, and **with low turnout it is effectively one on one**. 🎧 The podcast Landry referred to is the **Friday wrap-up on Marketplace** (10–15 minutes)",
        cn:"🧑‍🏫 **宏观经济助教答疑为问答形式**(周一18–19点、周二20–21点 PT,Zoom)。不同于微观助教,不提供补充讲课或习题讲解,**人少时近似一对一**。🎧 Landry 教授所指播客为 **Marketplace 周五总结**(10~15分钟)" },
      { kr:"⚠️ **LGST 는 조 편성 · Final Paper · Quiz #2 가 아직 Canvas 에 없습니다.** 지금 비어 보이는 것이 최종이 아닐 수 있습니다 — 동기 제보로, 여름 ACCT 교수가 중간고사 이후에 퀴즈 1개와 팀 케이스 1개를 나중에 추가한 사례가 있었습니다",
        en:"⚠️ **LGST has not posted groups, the final paper or Quiz #2 on Canvas yet.** What looks empty now may not be final — a classmate noted that the summer ACCT professor added a quiz and a team case after the midterm",
        cn:"⚠️ **LGST 的分组、期末论文与 Quiz #2 尚未在 Canvas 公布。** 目前的空白未必是最终状态 — 有同学提到暑期 ACCT 教授曾在期中后追加一次测验与一个小组案例" },
    ]},
    { date:"2026-08-29", items:[
      { kr:"🔴 **10월 주말이 3일입니다 — 목요일에 캠퍼스를 가셔야 합니다.** FNCE 실라버스가 10월을 **\"WEEKEND OF OCTOBER 8-9\"** 로 잡고 있고 **10/8(목)에 중간고사**를 봅니다. 여기에 LGST 종강·조별발표가 10/9–10 이라 **10/8–10 사흘**이 됩니다. 회사 일정을 지금 비워두세요",
        en:"🔴 **The October weekend is three days, and one of them is a Thursday.** The FNCE syllabus labels it the **\"weekend of October 8-9\"** with the **midterm on Thursday Oct 8**, while LGST holds its final sessions and group presentations on Oct 9-10 — so **Oct 8 through 10**. Block the time now",
        cn:"🔴 **10月上课为三天,且含周四。** FNCE 大纲标为 **\"WEEKEND OF OCTOBER 8-9\"**,**10/8(周四)期中考**;LGST 则于 10/9–10 结课并进行分组发表,合计 **10/8–10 三天**。请尽早空出行程" },
      { kr:"📐 **FNCE 첫 수업 슬라이드를 받아 전사와 대조했습니다.** 미국 GDP **$32.5조(1인당 약 $95k)** · 실질 GDP 기준연도 **2017 chained** · 소비 **GDP의 68%** · 유가 10% 지속 상승 → 헤드라인 **+0.5%p** 확정. ⚠️ 다만 **CPI 주거 비중의 정확한 숫자는 슬라이드에 없습니다** — 답안에 수치를 쓰지 마세요",
        en:"📐 **Pulled the FNCE slides and checked them against the transcript.** Confirmed: US GDP **$32.5tn (about $95k per person)**, real GDP in **2017 chained dollars**, consumption at **68% of GDP**, and a sustained 10% oil price rise adding **0.5pp** to headline inflation. ⚠️ The **exact CPI housing weight is not in the slides** — do not put a number on it in an exam answer",
        cn:"📐 **已取得 FNCE 首堂课幻灯片并与录音逐条核对。** 确认:美国 GDP **32.5万亿美元(人均约9.5万)**、实际GDP以 **2017 chained** 为基年、消费占 **GDP的68%**、油价持续上涨10%推升整体通胀 **0.5个百分点**。⚠️ 但 **CPI 住房权重的具体数字幻灯片中没有** — 答题时勿写数字" },
      { kr:"🎓 **첫 수업 두 개 정독 완료 — 실라버스에 없던 것들이 나왔습니다.** FNCE 는 시험을 **Respondus Lockdown Browser** 로 치르고 **퀴즈 4회 중 best 3**만 반영합니다. **Fed Challenge(10%)가 12/5** 로 확인돼 마감에 넣었고, **9/12 리뷰세션에서 Practice Midterm 을 배포**한다는 예고도 추가했습니다",
        en:"🎓 **Read through both first sessions, and details absent from the syllabus surfaced.** FNCE exams run on the **Respondus Lockdown Browser**, and only the **best 3 of 4 quizzes** count. The **Fed Challenge (10%) is confirmed for Dec 5** and has been added to the deadlines, along with the **practice midterm handed out at the Sep 12 review session**",
        cn:"🎓 **两门首堂课已通读,出现了大纲上没有的信息。** FNCE 考试使用 **Respondus Lockdown Browser**,**测验取4次中最佳3次**。已确认 **Fed Challenge(10%)于 12/5**,并加入截止列表,另补充 **9/12 复习课发放模拟期中**" },
      { kr:"📝 **LGST 퀴즈 형식이 확정됐습니다** — **3~4문항**, 객관식 또는 단답 2~3문장. 교수가 딱 하나 못박은 것은 **저자명과 제목 암기**이고, 세부 사실은 묻지 않는다고 했습니다. ⚠️ 그리고 **조별 발표의 조는 교수가 배정**합니다(자율 편성 아님)",
        en:"📝 **The LGST quiz format is now known** — **three to four questions**, multiple choice or short answers of two to three sentences. The one thing he insisted on is **knowing author names and titles**; he does not ask for factual detail. ⚠️ Also, **the professor assigns the presentation groups** — they are not self-selected",
        cn:"📝 **LGST 测验形式已确认** — **3~4题**,选择题或2~3句简答。教授唯一强调的是**记住作者姓名与标题**,不考细节。⚠️ 另外**分组由教授指定**,并非自由组队" },
      { kr:"🎯 **Innovation 대기 인원이 74명에서 70명으로 줄었습니다.** 🏥 그리고 **헬스케어 전공·집중을 고려하는 분**은 9/2 까지 이메일하면 9/11–12 주말에 열리는 Deputy Vice Dean 피드백 세션에 초대받습니다 (관심자만 해당)",
        en:"🎯 **The Innovation waitlist shrank from 74 to 70.** 🏥 Separately, **anyone considering a Healthcare Management major or concentration** can email by Sep 2 to be invited to a feedback session with the Deputy Vice Dean on the Sep 11–12 weekend (only if interested)",
        cn:"🎯 **Innovation 候补人数由74人减至70人。**🏥 另外,**有意主修或辅修医疗管理者**可在 9/2 前发邮件,以受邀参加 9/11–12 周末的副院长反馈座谈(仅限有兴趣者)" },
      { kr:"🔴 **FNCE 6130 실라버스 전문 확인 · 학기 전체 일정 5건 추가** — Quiz #2(10/4) · **중간 10/8(목)** · Quiz #3(11/5) · Quiz #4(11/29) · **기말 12/4(금)**. Quiz #1 외에는 아직 Canvas 에 등록되지 않아 실라버스 기준으로 넣었습니다",
        en:"🔴 **Read the full FNCE 6130 syllabus and added five term dates** — Quiz #2 (Oct 4), **midterm Thu Oct 8**, Quiz #3 (Nov 5), Quiz #4 (Nov 29) and the **final on Fri Dec 4**. Only Quiz #1 is on Canvas so far; the rest come from the syllabus",
        cn:"🔴 **已通读 FNCE 6130 大纲,新增全学期 5 个节点** — Quiz #2(10/4)· **期中 10/8(周四)**· Quiz #3(11/5)· Quiz #4(11/29)· **期末 12/4(周五)**。目前仅 Quiz #1 在 Canvas 上,其余依大纲录入" },
      { kr:"💻 **FNCE 시험은 대면인데 Canvas 로 온라인 시행입니다 — 노트북을 꼭 가져가세요** — 다른 과목과 반대라 헷갈리기 쉬운 지점입니다. 대신 **클로즈드북**이고 손글씨 단면 1장과 계산기만 허용, ⚠️ **아이패드로 만든 노트는 금지**입니다",
        en:"💻 **FNCE exams are in person but administered online through Canvas — bring a laptop** — the opposite of most other courses, so easy to get wrong. They are **closed-book**: one single-sided handwritten sheet and a calculator only, and ⚠️ **notes made on an iPad are not allowed**",
        cn:"💻 **FNCE 考试线下参加但通过 Canvas 在线进行 — 务必携带笔记本电脑** — 与其他课程相反,极易搞混。考试为**闭卷**,仅可带单面手写笔记一张与计算器,⚠️ **禁止用 iPad 制作的笔记**" },
      { kr:"🤖 **FNCE 퀴즈는 생성형 AI 와 팀 협업이 명시적으로 허용됩니다** — 실라버스에 *\"답이 아니라 힌트를 물어라, 시험장에는 AI 가 없다\"* 는 단서가 붙어 있습니다. 수업 중 노트북 금지 조항은 **없습니다**",
        en:"🤖 **FNCE quizzes explicitly permit generative AI and team collaboration** — with the caveat *\"ask for a hint, not the answer; you will not have AI in the exam.\"* There is **no** in-class laptop ban",
        cn:"🤖 **FNCE 测验明确允许生成式 AI 与团队协作** — 附带说明:*\"询问提示而非答案;考试时不会有 AI。\"* 课堂**没有**笔记本电脑禁令" },
      { kr:"⚠️ **FNCE 는 결석 4회 초과 시 사유 불문 낙제** · 시험은 중간 1 : 기말 2 배점에서 최저 1개를 버리며, 그래서 **중간 재응시·일정 변경이 없습니다**",
        en:"⚠️ **FNCE fails you after four absences**, excused or not · exams weight the midterm 1 : final 2 with the lowest of three dropped, which is why **no midterm retake or rescheduling exists**",
        cn:"⚠️ **FNCE 缺席超过四次即不及格**(无论理由)· 考试按期中 1 : 期末 2 计权并舍弃最低一项,因此**不设期中重考或改期**" },
    ]},
    { date:"2026-08-27", items:[
      { kr:"🔴 **STAT 6130 학기 전체 일정이 공개됐습니다** — Canvas 에 **12개 항목**이 한꺼번에 떴습니다. Homework 1~4 · Quiz 1~5 · 중간(36점) · 기말(36점). ⚠️ **Homework 4 가 100점으로 이 과목 최대 항목**이고 **12/23 마감**이라 연말과 겹칩니다",
        en:"🔴 **STAT 6130 posted its full term schedule** — **twelve items** appeared on Canvas at once: Homework 1 to 4, Quiz 1 to 5, a 36-point midterm and a 36-point final. ⚠️ **Homework 4 is worth 100 points, the largest single item**, and it is **due Dec 23**, right into the holidays",
        cn:"🔴 **STAT 6130 全学期安排已公布** — Canvas 上一次性出现 **12 项**:Homework 1~4 · Quiz 1~5 · 期中(36分)· 期末(36分)。⚠️ **Homework 4 达100分,为本课单项最高**,且 **12/23 截止**,与年末重叠" },
      { kr:"⏰ **마감 목록에 D-30 접기를 넣었습니다** — 항목이 27건으로 늘어 이번 주말 마감이 묻히지 않도록, 기본은 **30일 이내만** 보여주고 나머지는 '학기 전체 보기'로 펼칩니다",
        en:"⏰ **The deadline list now folds at D-30** — with 27 items, the near-term ones were getting buried. By default only the **next 30 days** show; the rest open under 'Show the rest of the term'",
        cn:"⏰ **截止列表新增 D-30 折叠** — 条目已达27项,为避免近期截止被淹没,默认仅显示**30天内**,其余点击「查看本学期全部」展开" },
      { kr:"✅ **FNCE 6130 Canvas 오픈 (8/26) · 이번 주말 준비물 없음** — Landry 교수 원문: *\"There is nothing you need to prepare or complete before our first class this weekend.\"* 다만 **Quiz #1 이 9/10(목) 23:59 PT 마감**으로 이미 올라와 있습니다",
        en:"✅ **FNCE 6130 opened on Canvas (Aug 26) with nothing to prepare** — Professor Landry: *\"There is nothing you need to prepare or complete before our first class this weekend.\"* That said, **Quiz #1 is already posted, due Thu Sep 10, 11:59 PM PT**",
        cn:"✅ **FNCE 6130 已于 8/26 上线,本周末无需准备** — Landry 教授原文:*\"There is nothing you need to prepare or complete before our first class this weekend.\"* 但 **Quiz #1 已发布,9/10(周四)23:59 PT 截止**" },
      { kr:"💻 **STAT 퀴즈는 Respondus LockDown Browser 가 필요합니다** — Canvas 에 연습용 퀴즈가 있으니 **시험 전에 미리 설치하고 한 번 돌려보세요.** 당일 설치하려다 시간을 버리는 경우가 많습니다",
        en:"💻 **STAT quizzes require the Respondus LockDown Browser** — there is a practice quiz on Canvas, so **install it and try it before the real thing.** Installing on the day is where people lose time",
        cn:"💻 **STAT 测验需要 Respondus LockDown Browser** — Canvas 上有练习测验,请**提前安装并试做一次**。当天临时安装最容易耽误时间" },
      { kr:"🧥 **플리스 재킷 수령** — 금 8/28 **08:30~09:25 Room 660** · 금요일 오전 수업 쉬는 시간에도 가능합니다",
        en:"🧥 **Fleece jacket pickup** — Fri Aug 28, **8:30 to 9:25 AM in Room 660**, and also during the Friday morning class break",
        cn:"🧥 **抓绒外套领取** — 8/28(周五)**08:30~09:25 · Room 660**,周五上午课间亦可" },
      { kr:"📌 **WEMBA Career Representatives 지원 마감 9/20** 추가 · **STAT 면제 시험 9/11(금) 첫 수업 시간** 도 마감 목록에 넣었습니다",
        en:"📌 Added **WEMBA Career Representatives applications, due Sep 20**, and the **STAT waiver exam on Fri Sep 11 during the first class**",
        cn:"📌 新增 **WEMBA Career Representatives 报名截止 9/20**,以及 **STAT 免修考试(9/11 周五首堂课时间)**" },
    ]},
    { date:"2026-08-23", items:[
      { kr:"🔴 **LGST 6120 리딩 10편 · Quiz #1 발견** — 실라버스 원문을 열어보니 교수 메일에 없던 내용이 있었습니다. **금 3편 · 토 7편**의 지정 리딩과, **이번 주말 클로즈드북 Quiz #1(배점 10%)**. 최상단 '지금 준비가 필요한 것' 섹션을 새로 만들어 전부 나열했습니다",
        en:"🔴 **Found ten LGST 6120 readings and Quiz #1** — the syllabus contains what the professor's email did not: **three readings for Friday, seven for Saturday**, plus a **closed-book Quiz #1 this weekend worth 10%**. A new top section, 'Prepare before class', now lists all of them",
        cn:"🔴 **发现 LGST 6120 十篇阅读与 Quiz #1** — 教学大纲中有教授邮件未提及的内容:**周五三篇、周六七篇**指定阅读,以及**本周末闭卷 Quiz #1(占10%)**。已新增顶部「现在需要准备的」栏目全部列出" },
      { kr:"🔄 **구성 개편** — What's New 는 메인에서 빼고 이 업데이트 내역으로만 옮겼습니다 · 액션 체크리스트는 삭제 · 대신 **'지금 준비가 필요한 것'** 을 최상단에 신설했습니다(체크 가능, 각자 브라우저에만 저장)",
        en:"🔄 **Layout change** — What's New has moved out of the main page into this changelog · the action checklist is gone · in its place, **'Prepare before class'** now sits at the top, with check-off saved in your own browser",
        cn:"🔄 **版面调整** — What's New 移出主页,仅保留于本更新记录 · 删除行动清单 · 改为顶部新增**「现在需要准备的」**,可勾选,仅存于本人浏览器" },
      { kr:"🔄 **Term 2 전면 개편** — Term 1(ACCT·BEPP·MGMT) 데이터를 전부 걷어내고 가을학기 6과목으로 교체 · 과목 카드·마감·수업 주말·Canvas 맵·블록위크를 새로 썼습니다",
        en:"🔄 **Rebuilt for Term 2** — all Term 1 content (ACCT, BEPP, MGMT) retired and replaced with the six Fall courses · course cards, deadlines, class weekends, the Canvas map and the block-week list are all new",
        cn:"🔄 **第二学期全面改版** — 移除第一学期(ACCT·BEPP·MGMT)全部内容,替换为秋季六门课 · 科目卡·截止·上课周末·Canvas 地图·Block Week 均已重写" },
      { kr:"📅 **가을 수업 주말 8회 확정** — 8/28–29 · 9/11 · 9/25 · 10/9 · 10/23 · 11/6 · 12/4 · 12/18. ⭐ **11/7~12/3 사이 4주가 통째로 빕니다**",
        en:"📅 **Eight class weekends locked** — Aug 28–29 · Sep 11 · Sep 25 · Oct 8 · Oct 23 · Nov 6 · Dec 4 · Dec 18. ⭐ **A four-week gap opens between Nov 7 and Dec 3**",
        cn:"📅 **秋季八个上课周末已确定** — 8/28–29 · 9/11 · 9/25 · 10/9 · 10/23 · 11/6 · 12/4 · 12/18。⭐ **11/7~12/3 空出整整四周**" },
      { kr:"🔢 **섹션 재편** — Term 2 배정은 Term 1 과 다릅니다. 과목 코드 끝자리가 섹션 번호(Wharton Reports ▸ My Class Lists) · 러닝팀은 유지",
        en:"🔢 **Sections reshuffled** — Term 2 differs from Term 1. The last digit of each course code is your section (Wharton Reports ▸ My Class Lists) · learning teams stay",
        cn:"🔢 **分班重编** — 第二学期与第一学期不同。课程代码末位即班号(Wharton Reports ▸ My Class Lists)· 学习小组不变" },
      { kr:"⏰ **블록위크 마감을 과목별로 표시했습니다** — Course Match 시스템은 12/19까지 열려 있지만 개별 ADD 마감은 10/5 · 11/23 · 12/7 로 훨씬 앞섭니다. 서울 개최였던 2건은 이미 마감(7/27)됐습니다",
        en:"⏰ **Block-week deadlines are now marked per course** — Course Match stays open until Dec 19, but individual ADD dates fall on Oct 5, Nov 23 and Dec 7. The two Seoul courses already closed on Jul 27",
        cn:"⏰ **Block Week 截止已按课标注** — Course Match 开放至 12/19,但各课 ADD 分别为 10/5 · 11/23 · 12/7。首尔两门已于 7/27 截止" },
    ]},
  ],

  /* ── 마감·일정 ─────────────────────────────────────────────────────── */
  deadlines: [
    {
      date:"2026-09-25", type:"session",
      title:{ kr:"WEMBA Careers · Networking Workshop", en:"WEMBA Careers · Networking Workshop", cn:"WEMBA Careers · Networking Workshop" },
      detail:{ kr:"주말 일정표의 Save the Date 항목 · 세부 시간 미공지",
              en:"A Save the Date on the weekend schedule · time not yet announced",
              cn:"周末日程表的 Save the Date · 具体时间未公布" },
    },
    {
      date:"2026-09-26", type:"quiz", course:"LGST",
      title:{ kr:"LGST 6120 Quiz #2 (클로즈드북 · 배점 10%)", en:"LGST 6120 Quiz #2 (closed book · 10%)", cn:"LGST 6120 Quiz #2(闭卷 · 占10%)" },
      detail:{ kr:"Unit II(Law) 주말 리딩이 범위 · 9/25 금요일 수업 = *Disclosures, Obligations to Customers and Employees* (\"Exit Interview\" 핸드아웃 · Williams v. Walker-Thomas Furniture · FTC v. Amazon 소장 등)",
              en:"Covers the Unit II (Law) weekend readings · the Sep 25 Friday session is *Disclosures, Obligations to Customers and Employees* (the \"Exit Interview\" handout, Williams v. Walker-Thomas Furniture, the FTC v. Amazon complaint and more)",
              cn:"范围为 Unit II(Law)周末阅读 · 9/25 周五课程为 *Disclosures, Obligations to Customers and Employees*(\"Exit Interview\" 讲义 · Williams v. Walker-Thomas Furniture · FTC v. Amazon 起诉书等)" },
    },
    {
      date:"2026-10-05T09:00", type:"registration", hard:true,
      title:{ kr:"10월 블록위크 ADD 마감 (9 AM PT)", en:"October block weeks — ADD deadline (9 AM PT)", cn:"10月 Block Week ADD 截止(9 AM PT)" },
      detail:{ kr:"10/12–15 사이클 전 과목 공통 · ⚠️ 이 시각 이후 추가 등록 불가",
              en:"Applies to the whole Oct 12–15 cycle · ⚠️ no adds after this moment",
              cn:"适用于 10/12–15 全部课程 · ⚠️ 此后不可加选" },
    },
    {
      date:"2026-10-13T09:00", type:"registration", hard:true,
      title:{ kr:"10월 블록위크 DROP·P/F 마감 (9 AM PT)", en:"October block weeks — DROP / P-F deadline (9 AM PT)", cn:"10月 Block Week DROP·P/F 截止(9 AM PT)" },
      detail:{ kr:"⭐ **수업 둘째 날 아침입니다.** 10/12 첫날 들어보고 판단해도 늦지 않아요 · ⚠️ **P/F 로 들으면 전공(major)에 인정되지 않습니다**",
              en:"⭐ **This is the morning of day two.** You can sit through Oct 12 and still decide · ⚠️ **P/F courses do not count toward a major**",
              cn:"⭐ **这是第二天上午。** 可先上完 10/12 再决定 · ⚠️ **P/F 不计入专业(major)**" },
    },
    {
      date:"2026-10-27", type:"paper", course:"LGST", hard:true,
      title:{ kr:"LGST 6120 개인 최종 페이퍼 (배점 25%)", en:"LGST 6120 individual final paper (25%)", cn:"LGST 6120 个人期末论文(占25%)" },
      detail:{ kr:"과제 내용은 **마지막 수업일 전에 공지**된다고 실라버스에 명시돼 있습니다 · LGST 는 10/10 에 끝나므로 종강 후 제출입니다",
              en:"The prompt will be **posted before the last day of class**, per the syllabus · LGST ends Oct 10, so this lands after the course finishes",
              cn:"大纲注明题目将于**最后一堂课前公布** · LGST 于 10/10 结课,故为课后提交" },
    },
    {
      date:"2026-11-23T09:00", type:"registration", hard:true,
      title:{ kr:"11/30–12/3 블록위크 ADD 마감 (9 AM PT)", en:"Nov 30 – Dec 3 block weeks — ADD deadline (9 AM PT)", cn:"11/30–12/3 Block Week ADD 截止(9 AM PT)" },
      detail:{ kr:"OIDD 6140 Innovation(SFO) · HCMG 8600(PHL) · ⚠️ **Innovation 은 대기 71명**이고 **Audit 도 불가** — 이 시각까지 자리가 안 나면 수강 불가",
              en:"OIDD 6140 Innovation (SFO) · HCMG 8600 (PHL) · ⚠️ **Innovation has 71 people waitlisted** and **audit is not allowed** — no seat by this moment means you are out",
              cn:"OIDD 6140 Innovation(SFO)· HCMG 8600(PHL)· ⚠️ **Innovation 候补71人**且**不可旁听** — 到此时刻无空位即无法修读" },
    },
    {
      date:"2026-12-07T09:00", type:"registration", hard:true,
      title:{ kr:"12/14–16 블록위크 ADD 마감 (9 AM PT)", en:"Dec 14–16 block week — ADD deadline (9 AM PT)", cn:"12/14–16 Block Week ADD 截止(9 AM PT)" },
      detail:{ kr:"LGST 6420 Accountable AI(SFO, Werbach) · ⚠️ **대기 42명**, **Audit 불가** · 가을 마지막 블록위크",
              en:"LGST 6420 Accountable AI (SFO, Werbach) · ⚠️ **42 waitlisted**, **no audit** · the last block week of the fall",
              cn:"LGST 6420 Accountable AI(SFO, Werbach)· ⚠️ **候补42人**,**不可旁听** · 秋季最后一门" },
    },
    {
      date:"2026-12-19T09:00", type:"registration",
      title:{ kr:"Course Match 가을학기 시스템 종료 (9 AM PT)", en:"Course Match closes for the fall term (9 AM PT)", cn:"Course Match 秋季学期关闭(9 AM PT)" },
      detail:{ kr:"시스템 자체가 닫히는 시각 · ⚠️ **개별 과목 마감은 이보다 훨씬 앞섭니다**",
              en:"When the system itself closes · ⚠️ **individual course deadlines land much earlier**",
              cn:"系统本身关闭的时刻 · ⚠️ **各课截止要早得多**" },
    },

    {
      date:"2026-09-10T23:59", type:"quiz", course:"FNCE", hard:true, new:false,
      title:{ kr:"FNCE 6130 Quiz #1 (15점)", en:"FNCE 6130 Quiz #1 (15 pts)", cn:"FNCE 6130 Quiz #1(15分)" },
      detail:{ kr:"범위 **Macroeconomic data · Production and economic growth** · Canvas 원문 9/11 06:59 UTC = **9/10(목) 23:59 PT** · **9/11 수업 전날 밤**입니다",
              en:"Covers **macroeconomic data, production and economic growth** · Canvas shows Sep 11 06:59 UTC = **Thu Sep 10, 11:59 PM PT** · **the night before the Sep 11 session**",
              cn:"范围 **宏观经济数据 · 生产与经济增长** · Canvas 原文 9/11 06:59 UTC = **9/10(周四)23:59 PT** · **即 9/11 上课前夜**" },
    },
    {
      date:"2026-09-12", type:"session", course:"FNCE", new:false,
      title:{ kr:"FNCE 리뷰세션 · Practice Midterm 배포", en:"FNCE review session · practice midterm handed out", cn:"FNCE 复习课 · 发放模拟期中" },
      detail:{ kr:"9/12(토) **마지막 1시간**을 리뷰에 씁니다 · 이 자리에서 **Practice Midterm 을 나눠주고 함께 풀이**한다고 첫 수업에서 예고했습니다",
              en:"The **last hour of Sat Sep 12** is a review session · he announced in class that a **practice midterm will be handed out and worked through** there",
              cn:"9/12(周六)**最后一小时**为复习课 · 首堂课预告将在此**发放并讲解模拟期中**" },
    },
    {
      date:"2026-12-05", type:"exam", course:"FNCE", hard:true, new:false,
      title:{ kr:"FNCE Fed Challenge 발표 (10%)", en:"FNCE Fed Challenge presentation (10%)", cn:"FNCE Fed Challenge 发表(10%)" },
      detail:{ kr:"**FOMC 위원 역할**을 맡아 하는 발표입니다 · 배점 **10%** · 세부 요강은 **중간고사 이후** 공지 예정",
              en:"A presentation in the role of an **FOMC member**, worth **10%** · the detailed brief comes **after the midterm**",
              cn:"以 **FOMC 委员**身份进行的发表 · 占 **10%** · 细则将于**期中考后**公布" },
    },
    {
      date:"2026-10-04T23:59", type:"quiz", course:"FNCE", hard:true, new:false,
      title:{ kr:"FNCE 6130 Quiz #2", en:"FNCE 6130 Quiz #2", cn:"FNCE 6130 Quiz #2" },
      detail:{ kr:"범위 **노동시장 · 소비 · 저축 · 투자** · 9/13(일) 오픈 → **10/4(일) 23:59 PT** · 실라버스 기준이며 Canvas 에는 아직 안 올라왔습니다",
              en:"Covers **the labor market, consumption, saving and investment** · opens Sun Sep 13, due **Sun Oct 4, 11:59 PM PT** · from the syllabus; not yet posted on Canvas",
              cn:"范围 **劳动力市场 · 消费 · 储蓄 · 投资** · 9/13(周日)开放 → **10/4(周日)23:59 PT** · 依大纲,Canvas 尚未发布" },
    },
    {
      date:"2026-10-08", type:"exam", course:"FNCE", hard:true, new:false,
      title:{ kr:"FNCE 6130 중간고사", en:"FNCE 6130 midterm", cn:"FNCE 6130 期中考试" },
      detail:{ kr:"⚠️ **10/8은 목요일입니다.** 실라버스가 10월을 **\"WEEKEND OF OCTOBER 8-9\"** 로 잡고 있고 LGST 는 10/9–10 에 종강·조별발표를 하므로, **10월 주말은 목·금·토 3일**이 됩니다 — 회사 일정을 미리 비워두세요 · 대면 응시하되 **Canvas + Lockdown Browser 로 시행 → 노트북 필수** · **클로즈드북**, 손글씨 노트 **단면 1장(8.5×11)** 과 계산기만 허용 · ⚠️ **재응시·일정 변경 없음** (못 보면 그 점수가 버려지는 것으로 처리)",
              en:"⚠️ **Oct 8 is a Thursday.** The syllabus labels October as **\"weekend of October 8-9\"** and LGST holds its final sessions on Oct 9-10, so **the October weekend runs Thursday through Saturday** — block the day off early · taken in person but **run on Canvas with the Lockdown Browser, so a laptop is required** · **closed-book**; one single-sided 8.5×11 sheet of handwritten notes and a calculator only · ⚠️ **no retakes or rescheduling** (a missed midterm simply becomes the dropped grade)",
              cn:"⚠️ **10/8 是周四。** 大纲将10月标为 **\"WEEKEND OF OCTOBER 8-9\"**,且 LGST 于 10/9–10 结课与分组发表,故 **10月上课为周四至周六共三天** — 请提前空出行程 · 线下参加但**通过 Canvas + Lockdown Browser 进行 → 必须带笔记本电脑** · **闭卷**,仅允许单面 8.5×11 手写笔记一张与计算器 · ⚠️ **不得重考或改期**(缺考即视为被舍弃的那一次成绩)" },
    },
    {
      date:"2026-11-05T23:59", type:"quiz", course:"FNCE", hard:true, new:false,
      title:{ kr:"FNCE 6130 Quiz #3", en:"FNCE 6130 Quiz #3", cn:"FNCE 6130 Quiz #3" },
      detail:{ kr:"범위 **경기변동 · 연준과 미국 통화정책** · 10/25(일) 오픈 → **11/5(목) 23:59 PT** · 실라버스 기준",
              en:"Covers **business cycles and the Fed / US monetary policy** · opens Sun Oct 25, due **Thu Nov 5, 11:59 PM PT** · from the syllabus",
              cn:"范围 **经济周期 · 美联储与美国货币政策** · 10/25(周日)开放 → **11/5(周四)23:59 PT** · 依大纲" },
    },
    {
      date:"2026-11-29T23:59", type:"quiz", course:"FNCE", hard:true, new:false,
      title:{ kr:"FNCE 6130 Quiz #4", en:"FNCE 6130 Quiz #4", cn:"FNCE 6130 Quiz #4" },
      detail:{ kr:"범위 **국제무역·국제금융 · 정부와 거시경제** · 11/8(일) 오픈 → **11/29(일) 23:59 PT** · 추수감사절 주간 직후입니다",
              en:"Covers **international trade and finance, government and the macroeconomy** · opens Sun Nov 8, due **Sun Nov 29, 11:59 PM PT** · right after Thanksgiving week",
              cn:"范围 **国际贸易与金融 · 政府与宏观经济** · 11/8(周日)开放 → **11/29(周日)23:59 PT** · 恰在感恩节周之后" },
    },
    {
      date:"2026-12-04", type:"exam", course:"FNCE", hard:true, new:false,
      title:{ kr:"FNCE 6130 기말고사", en:"FNCE 6130 final exam", cn:"FNCE 6130 期末考试" },
      detail:{ kr:"**12/4(금)** · **전 범위** · 대면 + **Canvas 온라인 시행 → 노트북 필수** · 클로즈드북, 손글씨 단면 1장 + 계산기 · 배점은 중간의 **2배**입니다",
              en:"**Fri Dec 4** · **cumulative** · in person but **administered online through Canvas, so bring a laptop** · closed-book, one single-sided handwritten sheet plus a calculator · counts **twice** the midterm",
              cn:"**12/4(周五)** · **全范围** · 线下参加但**通过 Canvas 在线进行 → 需带笔记本电脑** · 闭卷,单面手写一张 + 计算器 · 权重为期中的 **两倍**" },
    },
    {
      date:"2026-09-11", type:"session", course:"STAT", hard:true, new:true,
      title:{ kr:"STAT 6130 면제 시험 (첫 수업 시간)", en:"STAT 6130 waiver exam (during the first class)", cn:"STAT 6130 免修考试(首堂课时间)" },
      detail:{ kr:"**9/11(금) 첫 수업 시간에 시행** · 불합격해도 불이익 없고 첫 수업 녹화를 볼 수 있습니다 · 샘플 문제와 풀이가 **Canvas ▸ Files** 에 이미 올라와 있습니다(`6130_example_exam.pdf` · Exam 1~3 + solutions)",
              en:"**Given during the first class on Fri Sep 11** · no penalty for not passing, and a recording of the first session is available · a sample exam with solutions is already on **Canvas ▸ Files** (`6130_example_exam.pdf` plus Exams 1 to 3 with solutions)",
              cn:"**9/11(周五)首堂课时间进行** · 未通过无不利影响,可观看首堂课录像 · 样题与解答已在 **Canvas ▸ Files**(`6130_example_exam.pdf` 及 Exam 1~3 与解答)" },
    },
    {
      date:"2026-09-24T23:59", type:"quiz", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Quiz 1 (5점)", en:"STAT 6130 Quiz 1 (5 pts)", cn:"STAT 6130 Quiz 1(5分)" },
      detail:{ kr:"⚠️ **Respondus LockDown Browser 가 필요합니다.** Canvas 에 연습용 퀴즈(`Practice Quiz using New Quizzes`)가 있으니 **시험 전에 미리 설치하고 한 번 돌려보세요** — 당일 설치하려다 시간을 버리는 경우가 많습니다",
              en:"⚠️ **Requires the Respondus LockDown Browser.** Canvas has a `Practice Quiz using New Quizzes` — **install it and run the practice quiz beforehand**; installing on the day is where people lose time",
              cn:"⚠️ **需要 Respondus LockDown Browser。** Canvas 上有 `Practice Quiz using New Quizzes`,**请提前安装并试做一次** — 当天临时安装最容易耽误时间" },
    },
    {
      date:"2026-09-25T23:59", type:"paper", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Homework 1 (16점)", en:"STAT 6130 Homework 1 (16 pts)", cn:"STAT 6130 Homework 1(16分)" },
      detail:{ kr:"9/25(금) 수업 주말 첫날 밤 마감",
              en:"Due the night of Fri Sep 25, the first day of that class weekend",
              cn:"9/25(周五)上课周末首日夜间截止" },
    },
    {
      date:"2026-10-08T20:59", type:"quiz", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Quiz 2 (5점)", en:"STAT 6130 Quiz 2 (5 pts)", cn:"STAT 6130 Quiz 2(5分)" },
      detail:{ kr:"⚠️ **이 항목만 ET 자정 기준**으로 보입니다 — PT 로는 **저녁 8:59**. 첫 수업에서 확인하세요",
              en:"⚠️ **this one looks like an ET midnight deadline** — that is **8:59 PM PT**. Confirm in the first session",
              cn:"⚠️ **该项似按 ET 午夜计**,即 **PT 晚 8:59**。请在首堂课确认" },
    },
    {
      date:"2026-10-09T23:59", type:"paper", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Homework 2 (16점)", en:"STAT 6130 Homework 2 (16 pts)", cn:"STAT 6130 Homework 2(16分)" },
      detail:{ kr:"10/9(금) 수업 주말 첫날 밤 마감",
              en:"Due the night of Fri Oct 9",
              cn:"10/9(周五)上课周末首日夜间截止" },
    },
    {
      date:"2026-10-22T23:59", type:"quiz", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Quiz 3 (5점)", en:"STAT 6130 Quiz 3 (5 pts)", cn:"STAT 6130 Quiz 3(5分)" },
      detail:{ kr:"10/23 수업 주말 전날 밤",
              en:"The night before the Oct 23 class weekend",
              cn:"10/23 上课周末前夜" },
    },
    {
      date:"2026-10-23T20:59", type:"exam", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 중간고사 (36점)", en:"STAT 6130 midterm (36 pts)", cn:"STAT 6130 期中考试(36分)" },
      detail:{ kr:"**배점 36점** · ⚠️ **이 항목만 ET 자정 기준**으로 보입니다 — PT 로는 **저녁 8:59**. 첫 수업에서 확인하세요",
              en:"**36 points** · ⚠️ **this one looks like an ET midnight deadline** — that is **8:59 PM PT**. Confirm in the first session",
              cn:"**36分** · ⚠️ **该项似按 ET 午夜计**,即 **PT 晚 8:59**。请在首堂课确认" },
    },
    {
      date:"2026-11-05T23:59", type:"quiz", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Quiz 4 (5점)", en:"STAT 6130 Quiz 4 (5 pts)", cn:"STAT 6130 Quiz 4(5分)" },
      detail:{ kr:"**같은 날 Homework 3 도 마감**입니다",
              en:"**Homework 3 is due the same night**",
              cn:"**同日 Homework 3 亦到期**" },
    },
    {
      date:"2026-11-05T23:59", type:"paper", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Homework 3 (50점)", en:"STAT 6130 Homework 3 (50 pts)", cn:"STAT 6130 Homework 3(50分)" },
      detail:{ kr:"**배점 50점** — 앞의 두 과제(각 16점)보다 훨씬 큽니다 · Quiz 4 와 같은 날 마감이라 주의",
              en:"**50 points**, far heavier than the first two assignments (16 each) · same night as Quiz 4",
              cn:"**50分** — 远重于前两次作业(各16分)· 与 Quiz 4 同日截止" },
    },
    {
      date:"2026-12-03T23:59", type:"quiz", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Quiz 5 (5점)", en:"STAT 6130 Quiz 5 (5 pts)", cn:"STAT 6130 Quiz 5(5分)" },
      detail:{ kr:"마지막 퀴즈",
              en:"The last quiz",
              cn:"最后一次测验" },
    },
    {
      date:"2026-12-19T20:59", type:"exam", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 기말고사 (36점)", en:"STAT 6130 final exam (36 pts)", cn:"STAT 6130 期末考试(36分)" },
      detail:{ kr:"**배점 36점** · ⚠️ **이 항목만 ET 자정 기준**으로 보입니다 — PT 로는 **저녁 8:59**. 첫 수업에서 확인하세요",
              en:"**36 points** · ⚠️ **this one looks like an ET midnight deadline** — that is **8:59 PM PT**. Confirm in the first session",
              cn:"**36分** · ⚠️ **该项似按 ET 午夜计**,即 **PT 晚 8:59**。请在首堂课确认" },
    },
    {
      date:"2026-12-23T23:59", type:"paper", course:"STAT", hard:true, new:false,
      title:{ kr:"STAT 6130 Homework 4 (100점)", en:"STAT 6130 Homework 4 (100 pts)", cn:"STAT 6130 Homework 4(100分)" },
      detail:{ kr:"⚠️ **배점 100점으로 이 과목 최대 항목**입니다 · 12/23(수) 마감이라 **연말 일정과 겹칩니다**",
              en:"⚠️ **100 points, the largest single item in this course** · due Wed Dec 23, which **collides with the holidays**",
              cn:"⚠️ **100分,本课程单项最高** · 12/23(周三)截止,**与年末假期重叠**" },
    },
    {
      date:"2026-09-20", type:"registration", course:"WEMBA", hard:false, new:false,
      title:{ kr:"WEMBA Career Representatives 지원 마감", en:"WEMBA Career Representatives applications close", cn:"WEMBA Career Representatives 报名截止" },
      detail:{ kr:"1년차 대상 리더십 기회 · 커리어 프로그램 기획에 참여 · 신청서는 **Canvas ▸ Files** 의 `WEMBA Career Representative Program - Application 2026.pdf`",
              en:"A leadership opportunity for first years, shaping the career programming · the form is on **Canvas ▸ Files** as `WEMBA Career Representative Program - Application 2026.pdf`",
              cn:"面向一年级的领导机会,参与职业项目策划 · 申请表见 **Canvas ▸ Files** 的 `WEMBA Career Representative Program - Application 2026.pdf`" },
    },
    {
      date:"2026-09-16T17:00", type:"paper", course:"LGST", hard:true, new:true,
      title:{ kr:"🔴 LGST 조별 발표 · 주제 후보 제출 (조 대표)", en:"🔴 LGST group presentation · topic ideas due (one per group)", cn:"🔴 LGST 小组展示 · 提交候选主题(组代表)" },
      detail:{ kr:"**조 대표 1명이 주제 후보 2~3개를 각 한 문장 + 선호 순위**로 Feinstein 교수에게 메일 · 교수가 **그날 밤 조별 확정 주제를 회신**합니다\n\n⭐ 교수 안내가 **9월 초 브레인스토밍**이므로 **9/11–12 수업 주말에 조원끼리 정리**해 두면 딱 맞습니다",
              en:"**One representative emails 2 to 3 topic ideas**, one sentence each and ranked, to Prof. Feinstein · he **replies that night with each group's assigned topic**\n\n⭐ He asks groups to brainstorm in early September, so the **Sep 11–12 class weekend is the natural time** to settle it",
              cn:"**由一名组代表将2~3个候选主题(各一句话并排序)邮件给 Feinstein 教授** · 教授**当晚回复各组确定主题**\n\n⭐ 教授建议九月初完成头脑风暴,因此 **9/11–12 上课周末**正是敲定的时机" },
    },
    {
      date:"2026-10-08T17:00", type:"paper", course:"LGST", hard:true, new:true,
      title:{ kr:"🔴 LGST 조별 발표 · 슬라이드 제출 (조 대표)", en:"🔴 LGST group presentation · deck due (one per group)", cn:"🔴 LGST 小组展示 · 提交幻灯片(组代表)" },
      detail:{ kr:"**조 대표 한 명이 슬라이드를 Feinstein 교수에게 메일** · **10/8(목) 17:00 PT 마감**\n\n⚠️ **같은 날 FNCE 중간고사와 STAT Quiz 2 가 있습니다.** 슬라이드는 **10/8 이전에 끝내 두는 것이 사실상 필수**입니다",
              en:"**One representative emails the deck to Prof. Feinstein** · **due Thu Oct 8, 5:00 PM PT**\n\n⚠️ **The FNCE midterm and STAT Quiz 2 are the same day.** Finishing the deck **before Oct 8 is effectively mandatory**",
              cn:"**由一名组代表将幻灯片邮件给 Feinstein 教授** · **10/8(周四)17:00 PT 截止**\n\n⚠️ **当日还有 FNCE 期中与 STAT Quiz 2。** 幻灯片**须在 10/8 之前完成**" },
    },
    {
      date:"2026-09-14", type:"registration", course:"WEMBA", hard:true, new:true,
      title:{ kr:"🔴 Winter Global Modular Course (GMC) 지원 마감", en:"🔴 Winter Global Modular Course (GMC) applications close", cn:"🔴 冬季全球模块课程(GMC)报名截止" },
      detail:{ kr:"포털 `wharton-sa.terradotta.com` · ⭐ 좌측 필터 **「Open to」에서 `WEMBA28` + `WEMBAW28`** 를 선택해야 지원 가능한 과정이 보입니다. 리더십 벤처(Antarctica 등)도 같은 포털·같은 마감입니다\n\n**GMC 는 0.5 CU 선택과목**입니다 — 현지 4~6일, 정규 성적, 전공 인정 가능 · 등록비 $250~500 + 현지비 $500~2,000 · **항공권 별도** · 관심 있는 곳에 **복수 지원하고 순위를 매긴 뒤**, 결과 발표 후 **48시간 안에** 수락·거절합니다\n\n🔴 **일정이 겹치는 것을 알면서 등록하면 해당 과목에서 제적되고 향후 모듈러 과목 수강이 금지됩니다** (카탈로그 명문). 1/15 수업과 겹치는 **브라질·UAE·인도네시아(1/11–15)** 가 막힌 이유입니다. 충돌이 없는 겨울 과정은 **인도 12/27–31 · 사우디 1/3–7 · 베트남 1/4–8**\n\n⚠️ **1학년은 후순위**입니다 (정원 제한 과정은 2학년 우선). 보이는 목록도 사람마다 다르니 본인 계정에서 확인하세요. 안 들어도 졸업에 지장 없고, **2학년 필수 Global Business Week 로 해외 일정은 어차피 한 번 있습니다**",
              en:"Portal `wharton-sa.terradotta.com` · ⭐ select **`WEMBA28` and `WEMBAW28` under Open to** in the left filter to see what you can apply to. Leadership Ventures (Antarctica and others) share the portal and the deadline\n\n**A GMC is a 0.5 CU elective** — 4 to 6 days on site, letter graded, can count toward a major · registration $250–500 plus $500–2,000 on the ground · **airfare not included** · **apply to several and rank them**, then accept or decline **within 48 hours** of the decision\n\n🔴 **Knowingly registering into a schedule conflict can get you dropped from the course and barred from future modular courses** (catalogue text). That is why Brazil, the UAE and Indonesia (Jan 11–15) are blocked by the Jan 15 class. The winter options without a conflict are **India Dec 27–31, Saudi Arabia Jan 3–7 and Vietnam Jan 4–8**\n\n⚠️ **First years are lower priority** where enrollment is capped. What you see also varies by person, so check your own account. Skipping this has no effect on graduation, and **the required second-year Global Business Week already includes an overseas trip**",
              cn:"入口 `wharton-sa.terradotta.com` · ⭐ 须在左侧筛选**「Open to」中选择 `WEMBA28` 与 `WEMBAW28`** 才能看到可申请课程。领导力探险(如 Antarctica)使用同一入口与同一截止日\n\n**GMC 为 0.5 CU 选修课** — 现地4~6日、正式评分、可计入主修 · 注册费 $250~500,现地费用 $500~2,000 · **不含机票** · 可**同时申请多个并排序**,结果公布后需在 **48 小时内**接受或拒绝\n\n🔴 **明知日程冲突仍注册,可能被退课并禁止今后修读模块课程**(手册原文)。这正是与 1/15 上课日冲突的**巴西、UAE、印度尼西亚(1/11–15)**被封锁的原因。冬季无冲突的选项为**印度 12/27–31、沙特 1/3–7、越南 1/4–8**\n\n⚠️ **一年级为后位**(名额受限课程二年级优先)。可见列表因人而异,请在本人账户确认。不修读不影响毕业,且**二年级必修 Global Business Week 已包含一次海外行程**" },
    },
    {
      date:"2026-10-09", type:"paper", course:"LGST", hard:true, new:true,
      title:{ kr:"🔴 LGST 6120 조별 발표 (10/9–10/10)", en:"🔴 LGST 6120 group presentations (Oct 9–10)", cn:"🔴 LGST 6120 小组展示(10/9–10/10)" },
      detail:{ kr:"**형식** — 발표 8분(**10분 강제 종료**) + Q&A 10분 · 슬라이드 권장 · **전원 발언 불필요, 조원 전체 같은 성적** · 참석 못 하면 리서치·슬라이드로 분담 (참석 3명 미만이면 교수에게 즉시 메일)\n\n**내용** — 기업이 책임을 다하지 못한 사례 하나. 개요는 짧게, **시사점 1~2개를 깊게**. 넓게 훑지 말 것\n\n**발표일** — Section 1 은 10/9 Study Group 1·2·3·4 / 10/10 8·9·10, Section 2 는 10/9 Study Group 5·6·7·11 / 10/10 12·13·14\n\n🔴 **9/16(수) 17:00 PT 주제 후보 제출 · 10/8(목) 17:00 PT 슬라이드 제출** (조 대표 1명이 메일). ⚠️ **10/8 은 FNCE 중간고사와 같은 날**입니다",
              en:"**Format** — 8 minutes (**hard stop at 10**) plus about 10 minutes of Q&A · a deck is recommended · **not everyone speaks and the group shares one grade** · if you cannot attend, take on more research and slides (email the professor if fewer than three can attend)\n\n**Content** — one case where a firm fell short of its responsibilities. Brief overview, then **one or two implications in depth**\n\n**Schedule** — Section 1: Study Groups 1, 2, 3, 4 on Oct 9 and 8, 9, 10 on Oct 10 · Section 2: Study Groups 5, 6, 7, 11 on Oct 9 and 12, 13, 14 on Oct 10\n\n🔴 **Topic ideas due Wed Sep 16, 5 PM PT · deck due Thu Oct 8, 5 PM PT** (one representative emails). ⚠️ **Oct 8 is the same day as the FNCE midterm**",
              cn:"**形式** — 8分钟(**10分钟强制结束**)+ 约10分钟问答 · 建议使用幻灯片 · **无需全员发言,全组同一成绩** · 无法出席者以调研与幻灯片分担(出席少于3人须立即邮件告知教授)\n\n**内容** — 选取一起企业失责事件。简述经过,**深入探讨1~2个启示**\n\n**展示安排** — Section 1:10/9 第1·2·3·4组,10/10 第8·9·10组 · Section 2:10/9 第5·6·7·11组,10/10 第12·13·14组\n\n🔴 **9/16(周三)17:00 PT 提交候选主题 · 10/8(周四)17:00 PT 提交幻灯片**(由组代表邮寄)。⚠️ **10/8 与 FNCE 期中考试同日**" },
    },
  ],

  /* ── 과목 카드 ─────────────────────────────────────────────────────── */
  courses: [
    {
      code:"LGST 6120", color:"#ffb3c7",
      name:{ kr:"Responsibility in Business · Brian Feinstein", en:"Responsibility in Business · Brian Feinstein", cn:"Responsibility in Business · Brian Feinstein" },
      headline:{ kr:"🚀 8/28 개강 · 1st Half (8/28–10/10) · 0.5 CU · 교재 없음", en:"🚀 Starts Aug 28 · first half (Aug 28 – Oct 10) · 0.5 CU · no textbook", cn:"🚀 8/28 开课 · 上半学期(8/28–10/10)· 0.5 CU · 无教材" },
      points:[
        { new:true, kr:"👤 **Brian D. Feinstein** · Associate Professor, Legal Studies & Business Ethics · bdfeinst@wharton.upenn.edu · **오피스아워: 수업 당일 SF 현장에서 세션 직전·직후**, 그 외 평일은 Zoom(필라델피아 연구실) — 메일로 예약",
          en:"👤 **Brian D. Feinstein** · Associate Professor, Legal Studies & Business Ethics · bdfeinst@wharton.upenn.edu · **office hours: in SF on class days, immediately before or after sessions**; otherwise Zoom from Philadelphia on most weekdays, by email",
          cn:"👤 **Brian D. Feinstein** · Legal Studies & Business Ethics 副教授 · bdfeinst@wharton.upenn.edu · **办公时间:上课日在 SF,课前课后**;其余工作日经邮件预约 Zoom(费城办公室)" },
        { new:true, kr:"📊 **배점** — Values Paper 5% · **인클래스 퀴즈 20%(각 10%)** · **Class Engagement 25%** · 그룹 발표 25% · 최종 페이퍼 25%. 참여 비중이 25%라 결석·침묵의 비용이 큽니다",
          en:"📊 **Grading** — Values Paper 5% · **in-class quizzes 20% (10% each)** · **class engagement 25%** · group presentation 25% · final paper 25%. Engagement at 25% means silence is expensive",
          cn:"📊 **评分** — Values Paper 5% · **课堂测验 20%(各10%)** · **课堂参与 25%** · 小组展示 25% · 期末论文 25%。参与占25%,缺席与沉默代价不小" },
        { new:true, kr:"⚠️ **인클래스 퀴즈 2회 (8/29 완료 · 9/26), 클로즈드북.** ⭐ **3~4문항**이고 **객관식 또는 단답 2~3문장**입니다 · 교수가 딱 하나 못박은 것은 **저자명과 제목은 반드시 외우라**는 것 · 세부 사실 암기는 요구하지 않고 각 리딩의 테제와 반대 논거를 이해했는지를 봅니다. 리딩을 실제로 읽었는지 확인하는 시험이라고 명시했습니다 — *\"evidence that you have grappled with the core concepts addressed in the readings\"*",
          en:"⚠️ **Two closed-book in-class quizzes (Aug 29 done, Sep 26).** ⭐ **Three to four questions**, multiple choice or two to three sentence short answers · the one thing he insisted on is that **you must know author names and titles**, not factual minutiae — just the thesis of each reading and the counterarguments. The professor states they check that you actually engaged with the readings — *\"evidence that you have grappled with the core concepts addressed in the readings\"*",
          cn:"⚠️ **两次闭卷课堂测验(8/29 已完成 · 9/26)。** ⭐ **3~4题**,选择题或2~3句简答 · 教授唯一强调的是**必须记住作者姓名与标题**,不考细节,只看是否理解各篇论点与反驳。 教授明确其目的是检验是否真正阅读 — *\"evidence that you have grappled with the core concepts addressed in the readings\"*" },
        { new:true, kr:"🎤 **그룹 발표(25%)** — 마지막 수업 세션에서 **기업 스캔들이나 무책임 사례**를 분석하고 교훈을 정리 · ⚠️ **조는 교수가 배정합니다**(자율 편성 아님) · 교수는 *\"덜 알려진 사례 + 독창적 각도\"* 를 선호한다고 밝혔습니다 · 원칙적으로 조원 전원 동일 점수",
          en:"🎤 **Group presentation (25%)** — in the final sessions, analyse **a corporate scandal or failure to act responsibly** and draw out lessons · all members receive the same grade barring extremes",
          cn:"🎤 **小组展示(25%)** — 最后几堂课分析**企业丑闻或不负责任案例**并总结教训 · 原则上组员同分" },
        { new:true, kr:"📄 **최종 페이퍼 10/27 제출(25%)** — 과제 내용은 마지막 수업일 전에 공지 · 3개 모듈 구성: **Ethics → Law → Politics**",
          en:"📄 **Final paper due Oct 27 (25%)** — the prompt is posted before the last day of class · the course runs in three modules: **Ethics, Law, Politics**",
          cn:"📄 **期末论文 10/27 提交(25%)** — 题目于最后一堂课前公布 · 课程分三模块:**Ethics → Law → Politics**" },
        { kr:"🤖 **수업 중 AI 사용 금지**가 실라버스에 명시돼 있습니다",
          en:"🤖 The syllabus states that **AI may not be used during class sessions**",
          cn:"🤖 大纲明确规定**课堂上不得使用 AI**" },
        { kr:"📂 자료가 **세 곳으로 갈립니다** — 리딩 = Course Materials @ Penn Libraries · Study.Net / 연습문제 핸드아웃 = Files 폴더",
          en:"📂 Materials sit in **three places** — readings in Course Materials @ Penn Libraries and Study.Net, exercise handouts in Files",
          cn:"📂 资料分**三处** — 阅读在 Course Materials @ Penn Libraries 与 Study.Net,练习讲义在 Files" },
      ],
    },
    {
      code:"FNCE 6130", color:"#0b051d",
      name:{ kr:"Macroeconomics & the Global Economy · Anthony Landry", en:"Macroeconomics & the Global Economy · Anthony Landry", cn:"宏观经济与全球经济环境 · Anthony Landry" },
      headline:{ kr:"✅ 개강 완료 · Full Term (8/28–12/5) · 1.0 CU · 📄 실라버스 공개", en:"✅ Under way · full term (Aug 28 – Dec 5) · 1.0 CU · 📄 syllabus posted", cn:"✅ 已开课 · 全学期(8/28–12/5)· 1.0 CU · 📄 大纲已公布" },
      points:[
        { new:true, kr:"💻 **수업 중 노트북 금지 조항은 없습니다** — 실라버스에 laptop·전자기기 관련 규정 자체가 없어요. 다만 **시험을 Canvas + Respondus Lockdown Browser 로 시행**하므로 **10/8 · 12/4 에는 노트북이 반드시 필요합니다** — 첫 수업에서 **AI 때문에 대면 비중을 높였다**고 밝혔고 설치·사용법은 다음 수업에 안내한다고 했습니다. 📷 강의 촬영·녹화는 화면에 띄운 것 포함 엄금(윤리강령 위반 처리)",
          en:"💻 **No in-class laptop ban** — the syllabus has no clause about laptops or electronic devices at all. But **exams run on Canvas with the Respondus Lockdown Browser**, so **you must bring a laptop on Oct 8 and Dec 4** — he said in class that in-person weight was raised because of AI, and setup instructions come next session. 📷 Photographing or recording class, including anything projected, is strictly prohibited and treated as an ethics violation",
          cn:"💻 **课堂无笔记本电脑禁令** — 大纲中完全没有关于笔记本或电子设备的条款。但**考试通过 Canvas + Respondus Lockdown Browser 进行**,因此 **10/8 与 12/4 必须携带笔记本电脑** — 教授称因AI而提高线下比重,安装说明下节课公布。📷 严禁拍摄或录制课堂内容(含投影画面),按违反道德准则处理" },
        { new:true, kr:"📝 **시험은 클로즈드북 · 손글씨 노트 단면 1장(8.5×11)만** — ⚠️ **타이핑·인쇄한 노트, 아이패드나 태블릿으로 만든 노트는 금지**입니다. 계산기는 허용 · 팀 공동 작성이나 슬라이드·솔루션 통째 복사도 금지",
          en:"📝 **Exams are closed-book with one single-sided 8.5×11 sheet of handwritten notes** — ⚠️ **typed or printed notes, including anything made on an iPad or tablet, are not allowed.** Calculators are permitted; the sheet may not be prepared collaboratively or copy wholesale from slides or solutions",
          cn:"📝 **考试闭卷,仅可带单面 8.5×11 手写笔记一张** — ⚠️ **禁止打字或打印的笔记,包括用 iPad/平板制作的笔记。** 允许计算器;不得合作撰写或整段照抄幻灯片与答案" },
        { new:true, kr:"🤖 **퀴즈는 생성형 AI 와 팀 협업 모두 허용됩니다** — Landry 교수 원문: *\"막혔을 때는 답이 아니라 힌트나 설명을 물으세요. 생각을 대체하는 게 아니라 강화하는 데 쓰라는 뜻입니다. 시험장에는 AI 가 없습니다.\"*",
          en:"🤖 **Quizzes explicitly allow both generative AI and team collaboration** — Professor Landry: *\"When you get stuck, consider asking AI for a hint or an explanation rather than the answer. The goal is to use AI to strengthen your thinking, not replace it. You will not have AI when you take the exams.\"*",
          cn:"🤖 **测验明确允许使用生成式 AI 与团队协作** — Landry 教授原文:*\"卡住时请向 AI 询问提示或解释,而非答案。目的是强化而非取代你的思考。考试时不会有 AI。\"*" },
        { new:true, kr:"⚠️ **결석 4회를 넘으면 사유를 불문하고 낙제**입니다 · 지각도 명시적으로 지적돼 있어요. 🎯 시험은 **중간 1 : 기말 2** 배점에서 **가장 낮은 하나를 버립니다** — 그래서 중간 재응시나 일정 변경이 아예 없습니다",
          en:"⚠️ **More than four absences means you cannot pass**, excused or not · punctuality is called out too. 🎯 Exams weight the **midterm 1 : final 2**, and **the lowest of the three grades is dropped** — which is why no midterm retake or rescheduling is offered",
          cn:"⚠️ **缺席超过四次即无法及格**(无论是否有正当理由)· 大纲亦强调守时。🎯 考试按**期中 1 : 期末 2** 计权,并**舍弃三项成绩中最低的一项** — 因此不设期中重考或改期" },
        { new:true, kr:"🎯 **배점은 시험 70% · 퀴즈 10% · Fed Challenge 10% · 참여 10%** 입니다(실라버스 확정) · **퀴즈는 4회 중 best 3**만 반영되고, 시험은 **중간 1 : 기말 2** 중 최저 하나를 버립니다 · **Fed Challenge 10%** 는 **12/5 발표**(FOMC 위원 역할, 세부 요강은 중간고사 이후) · 참여 10%",
          en:"🎯 **Exams 70%, quizzes 10%, Fed Challenge 10%, participation 10%** per the syllabus · **best 3 of 4 quizzes** count, and among exams the lowest of three grades is dropped (midterm 1 : final 2) · the **Fed Challenge is 10%**, presented **Dec 5** as an FOMC-member role play, with details after the midterm · participation 10%",
          cn:"🎯 **考试70% · 测验10% · Fed Challenge 10% · 参与10%**(大纲确定)· **测验取4次中最佳3次**,考试按期中1:期末2计权并舍弃最低一项 · **Fed Challenge 占10%**,**12/5** 以FOMC委员角色发表,细则期中后公布 · 参与10%" },
        { new:true, kr:"💬 **원격 질문은 이메일이 아니라 Canvas Discussion Board** 로 하라고 교수가 요청했습니다 · TA 2명 Zoom 오피스아워 **월 6–7시 · 화 8–9시** · 📻 권유 습관: 경제지 1종 정기 구독, 시간이 없으면 **금요일 Marketplace 팟캐스트 첫 10분**",
          en:"💬 The professor asks that remote questions go to the **Canvas Discussion Board rather than email** · two TAs hold Zoom office hours **Mon 6–7 and Tue 8–9** · 📻 his habit request: subscribe to one business daily, or if time is short, **the first ten minutes of the Friday Marketplace podcast**",
          cn:"💬 教授要求远程提问走 **Canvas Discussion Board 而非邮件** · 两位助教 Zoom 答疑 **周一6–7 · 周二8–9** · 📻 建议习惯:订阅一份财经媒体,时间紧则听**周五 Marketplace 播客前十分钟**" },
        { new:true, kr:"🔴 **퀴즈 규칙이 바뀌었습니다 — 시도 3회 · 최고점 반영 · 정오답 확인 가능.** 교수가 다른 섹션 요청을 수락해 8/29 수업 중 발표했고 Canvas 설정도 이미 바뀌었습니다. **1차를 그냥 풀어보고 오답을 확인한 뒤 2·3차**를 보는 것이 설계 의도입니다",
          en:"🔴 **The quiz rules changed — three attempts, highest score counts, and you can see which answers were right.** He accepted another section's request, announced it in the Aug 29 class, and Canvas is already reconfigured. The intent is to **take attempt 1 cold, review the misses, then attempt 2 and 3**",
          cn:"🔴 **测验规则已变更 — 可考3次 · 取最高分 · 可查看对错。** 教授接受了其他班的请求,于 8/29 课上宣布,Canvas 设置亦已更改。设计意图是**先裸考第一次,查看错题后再考第2、3次**" },
        { new:true, kr:"📋 **시험 형식이 공개됐습니다** — 교수 원문: *\"대부분 **3분의 2에서 4분의 3이 객관식**이고 짧은 서술이 조금. 제가 이야기로 끌고 가면 **increase, decrease, appreciate, depreciate 를 채우고 숫자를 대입**하는 식입니다.\"* 거대 모형 풀이는 없습니다",
          en:"📋 **The exam format is now known** — in his words: *\"most of the time it is **two-thirds to three-quarters multiple choice**, then some short essay. I walk you through a story and **you fill in increase, decrease, appreciate, depreciate, and plug in some numbers.**\"* No large model derivations",
          cn:"📋 **考试形式已公布** — 教授原话:*\"大多数情况下 **三分之二至四分之三为选择题**,另有少量简答。我会用一个情境带着你走,**你只需填入 increase、decrease、appreciate、depreciate 并代入数字。**\"* 不考大型模型推导" },
        { new:true, kr:"⚠️ **진짜 난이도는 강의 사이의 연결입니다** — 교수 원문: *\"이 수업은 소설 같습니다. **각 강의는 그 자체로는 꽤 쉽습니다. 그런데 강의들을 연결하기 시작해야 하고, 진짜 어려움은 거기서 옵니다.**\"* 🧑‍🏫 TA Zoom 오피스아워는 **월 18–19시 · 화 20–21시 PT**이고, 강의가 아니라 **Q&A 형식**이라 참석자가 적으면 사실상 1:1입니다",
          en:"⚠️ **The real difficulty is linking the lectures** — in his words: *\"the class is a little bit like a novel. **Each lecture by itself is quite easy. But you are going to have to start linking those classes, and this is where the real challenge is going to come.**\"* 🧑‍🏫 TA Zoom office hours are **Mon 6–7 PM and Tue 8–9 PM PT**, run as **Q&A rather than a lecture**, so with low turnout it is effectively one on one",
          cn:"⚠️ **真正的难点在于把各讲连起来** — 教授原话:*\"这门课有点像一部小说。**每一讲本身都相当容易,但你必须开始把它们串联起来,真正的挑战就在那里。**\"* 🧑‍🏫 助教 Zoom 答疑为 **周一18–19点 · 周二20–21点 PT**,采 **问答形式**而非讲课,人少时近似一对一" },
        { kr:"📕 **교재: *Macroeconomics* 6판 · Charles Jones · ISBN 9781324063612** — 하드카피·ebook 둘 다 가능",
          en:"📕 **Textbook: *Macroeconomics*, 6th ed · Charles Jones · ISBN 9781324063612** — hardcopy or ebook",
          cn:"📕 **教材:*Macroeconomics* 第6版 · Charles Jones · ISBN 9781324063612** — 纸质或电子版均可" },
        { kr:"🗓 섹션 2 기준 8/28–29: **금 9:30–12:30 · 토 1:00–4:00, Room 615**",
          en:"🗓 Section 2 on Aug 28–29: **Fri 9:30–12:30 and Sat 1:00–4:00, Room 615**",
          cn:"🗓 第2班 8/28–29:**周五 9:30–12:30,周六 1:00–4:00,Room 615**" },
        { kr:"⏳ 1.0 CU 로 가을 내내 이어지며 **12/5 에 끝납니다.** 12/18 마지막 주말에는 이 과목이 없어요",
          en:"⏳ A 1.0 CU course running through **Dec 5**. It does not appear on the final weekend of Dec 18",
          cn:"⏳ 1.0 CU 贯穿秋季,至 **12/5** 结束。12/18 最后周末无此课" },
      ],
    },
    {
      code:"STAT 6130", color:"#8e8a99",
      name:{ kr:"Regression Analysis for Management · Richard Waterman", en:"Regression Analysis for Management · Richard Waterman", cn:"回归分析 · Richard Waterman" },
      headline:{ kr:"📅 9/11 시작 · 12/19까지 · 1.0 CU · 📕 교재 3권 · ✅ Canvas 열림", en:"📅 Starts Sep 11 · through Dec 19 · 1.0 CU · 📕 three books · ✅ Canvas open", cn:"📅 9/11 开始 · 至 12/19 · 1.0 CU · 📕 三本教材 · ✅ Canvas 已开放" },
      points:[
        { new:true, kr:"👤 **Richard Waterman** · 108 Steinberg Conference Center · waterman@wharton.upenn.edu · ⚠️ **모든 메일 제목에 \"WEMBA WEST\" 를 넣어달라**고 실라버스에 명시돼 있습니다 · TA 는 아직 미정(TBD)",
          en:"👤 **Richard Waterman** · 108 Steinberg Conference Center · waterman@wharton.upenn.edu · ⚠️ the syllabus asks that you **put \"WEMBA WEST\" in the subject line of every email** · TA still TBD",
          cn:"👤 **Richard Waterman** · 108 Steinberg Conference Center · waterman@wharton.upenn.edu · ⚠️ 大纲要求**所有邮件主题须含 \"WEMBA WEST\"** · 助教待定" },
        { new:true, kr:"⚠️ **BAUR(*Business Analysis Using Regression*) ISBN 9780387983561 은 하드카피만 있고 ebook 이 없습니다.** 9/11 개강 전 배송을 고려해 지금 주문하세요",
          en:"⚠️ **BAUR (*Business Analysis Using Regression*), ISBN 9780387983561, is hardcopy only.** Order now to have it before the Sep 11 start",
          cn:"⚠️ **BAUR(*Business Analysis Using Regression*)ISBN 9780387983561 仅纸质版。** 请现在下单以赶在 9/11 开课前送达" },
        { new:true, kr:"🗂 **기출이 이미 올라와 있습니다** — Exam 1·2·3 문제·정답·결과 분포 + example exam + 정답까지. 학기 초에 난이도를 가늠해두면 편합니다",
          en:"🗂 **Past exams are already posted** — Exams 1, 2 and 3 with solutions and score distributions, plus an example exam with answers. Worth a look early to calibrate",
          cn:"🗂 **历年试题已上传** — Exam 1·2·3 试题、答案与分数分布,另有样卷及答案。学期初浏览有助于把握难度" },
        { kr:"📗 나머지 2권 — *BBS: A Casebook* 9780387983547 · *Statistics for Business* 3판 9780134497167 (둘 다 ebook 가능)",
          en:"📗 The other two — *BBS: A Casebook* 9780387983547 · *Statistics for Business*, 3rd ed 9780134497167 (both available as ebooks)",
          cn:"📗 另两本 — *BBS: A Casebook* 9780387983547 · *Statistics for Business* 第3版 9780134497167(均有电子版)" },
      ],
    },
    {
      code:"MKTG 6110", color:"#c8385f",
      name:{ kr:"Marketing Management · Sharif", en:"Marketing Management · Sharif", cn:"市场营销管理 · Sharif" },
      headline:{ kr:"📅 11/6 시작 · 2nd Half (11/6–12/19) · 0.5 CU · 교재 없음", en:"📅 Starts Nov 6 · second half (Nov 6 – Dec 19) · 0.5 CU · no textbook", cn:"📅 11/6 开始 · 下半学期(11/6–12/19)· 0.5 CU · 无教材" },
      points:[
        { kr:"⏳ 학기 후반부 과목이라 **11/6 수업 주말부터** 시작합니다. Canvas 사이트도 그때 열립니다 — 지금은 신경 쓸 것이 없어요",
          en:"⏳ A second-half course beginning on the **Nov 6 class weekend**; the Canvas site opens then too. Nothing to do for now",
          cn:"⏳ 下半学期课程,自 **11/6 上课周末**开始,Canvas 届时开放。目前无需准备" },
        { kr:"📌 세분화·타겟팅·브랜딩·가격·유통·프로모션을 케이스 중심으로 다루는 코어 과목 · **Marketing 계열 상위 과목의 선수 과목**입니다",
          en:"📌 The core marketing course, taught largely through cases · it is also the **prerequisite for most upper-level marketing electives**",
          cn:"📌 市场营销核心课,以案例为主 · 也是**多数高阶营销选修课的先修课**" },
      ],
    },
  ],

  /* ── 블록위크 ─────────────────────────────────────────────────────── */
  blockWeek: {
    note: { kr:"3–4일 압축 선택과목(보통 0.5 CU, 졸업 19 CU에 포함) · 정규 일정에 내장된 여유는 **1 CU = 블록위크 2개** 뿐입니다 · ⚠️ **전공(major)엔 Graded 만 인정** — P/F 불인정 · **전공 = 코어 외 4 CU = 블록위크 8개**, 컨센트레이션 = 3 CU = 6개 · PHL·SFO 혼합 수강 가능 · ⏰ **ADD·DROP 마감은 과목마다 다르고 대부분 블록위크 직전**입니다 — Course Match 시스템이 12/19까지 열려 있다는 것과 개별 마감은 별개예요 · DROP 마감은 대개 **수업 둘째 날 아침**이라 첫날 들어보고 판단할 수 있습니다 · 상세·실라버스·Booklist: Canvas ▸ Files ▸ Course Materials ▸ Term 5",
            en:"Electives compressed into 3–4 days (usually 0.5 CU, counting toward the 19 CU needed to graduate) · the schedule builds in only **1 CU, i.e. two block weeks** · ⚠️ **only Graded courses count toward a major**, P/F does not · **a major is 4 CU beyond the core, so eight block weeks**; a concentration is 3 CU, or six · mix PHL and SFO freely · ⏰ **ADD and DROP deadlines are per course and mostly sit just before each block week** — the fact that Course Match stays open until Dec 19 is a separate thing · DROP usually closes on the **morning of day two**, so you can attend day one and still decide · details, syllabi and booklist: Canvas ▸ Files ▸ Course Materials ▸ Term 5",
            cn:"3–4天压缩选修(通常 0.5 CU,计入毕业19 CU)· 常规安排仅内置 **1 CU 即两门** · ⚠️ **专业只认 Graded**,P/F 不计 · **专业 = 核心外 4 CU = 八门**;concentration = 3 CU = 六门 · 可混选 PHL 与 SFO · ⏰ **ADD·DROP 因课而异,多在各 Block Week 前夕** — 与 Course Match 开放至 12/19 是两回事 · DROP 通常在**第二天上午**截止,可先上第一天再决定 · 详情、大纲与书单:Canvas ▸ Files ▸ Course Materials ▸ Term 5" },
    options: [
      { code:"MKTG 7340", meta:{ kr:"🟢 신청 가능 · SFO · 10/12–15 · Nave · ADD 10/5 · DROP·P/F 10/13 · Audit O · 대기 없음",
        en:"🟢 Open · SFO · Oct 12–15 · Nave · ADD Oct 5 · DROP/PF Oct 13 · audit OK · no waitlist",
        cn:"🟢 可选 · SFO · 10/12–15 · Nave · ADD 10/5 · DROP·P/F 10/13 · 可旁听 · 无候补" },
        title:{ kr:"Augmented Creativity (Course Match 표기는 'Creativity')", en:"Augmented Creativity (listed in Course Match as 'Creativity')", cn:"Augmented Creativity(Course Match 标注为 'Creativity')" },
        desc:{ kr:"AI 가 ideation 부터 prototyping 까지 창작 과정을 어떻게 바꾸는지 · SIT 등 체계적 발상 기법 실습 · vibe coding·음악·영상 도구 · 팀 프로젝트 + 최종 발표 포함(나흘로 끝나지 않습니다) · 👤 Nave 는 Wharton Teaching Excellence Award(2020)·P&Q 40 under 40(2021) 수상",
                en:"How AI reshapes creation from ideation through prototyping · hands-on structured techniques such as SIT · vibe coding, music and video tools · includes a team project and final presentation, so it runs beyond the four days · 👤 Nave won the Wharton Teaching Excellence Award (2020) and P&Q Best 40-Under-40 (2021)",
                cn:"AI 如何改变从构思到原型的创作流程 · SIT 等结构化方法实操 · vibe coding、音乐与视频工具 · 含小组项目与期末展示,不止四天 · 👤 Nave 获 Wharton 教学卓越奖(2020)与 P&Q 40岁以下最佳教授(2021)" } },
      { code:"MKTG 8530", meta:{ kr:"🟢 신청 가능 · PHL · 10/12–15 · Karol/Norton · ADD 10/5",
        en:"🟢 Open · PHL · Oct 12–15 · Karol/Norton · ADD Oct 5",
        cn:"🟢 可选 · PHL · 10/12–15 · Karol/Norton · ADD 10/5" },
        title:{ kr:"Designing & Deploying AI Agents", en:"Designing & Deploying AI Agents", cn:"AI 代理设计与部署" },
        desc:{ kr:"", en:"", cn:"" } },
      { code:"MGMT 7640", meta:{ kr:"🔴 **잔여 2석 / 37석** · SFO · 10/12–14 (3일) · Rosenkopf · ADD 10/5",
        en:"🔴 **2 seats left of 37** · SFO · Oct 12–14 (3 days) · Rosenkopf · ADD Oct 5",
        cn:"🔴 **余2席 / 37席** · SFO · 10/12–14(3天)· Rosenkopf · ADD 10/5" },
        title:{ kr:"Tech in the SF Bay Area", en:"Tech in the SF Bay Area", cn:"湾区科技" },
        desc:{ kr:"⚠️ 3일이라 10/14 에 끝납니다 · Philly 코호트는 10/15 수업이 있어 10월 사이클 중 이 과목만 가능",
                en:"⚠️ Three days, ending Oct 14 · the Philly cohort has class Oct 15, so this is their only October option",
                cn:"⚠️ 仅三天,10/14 结束 · Philly 班 10/15 有课,10月只能选这门" } },
      { code:"LGST 7500", meta:{ kr:"🟢 신청 가능 · PHL · 10/12–15 · Conti-Brown · ADD 10/5 · 30석 중 20석 여유",
        en:"🟢 Open · PHL · Oct 12–15 · Conti-Brown · ADD Oct 5 · 20 of 30 seats free",
        cn:"🟢 可选 · PHL · 10/12–15 · Conti-Brown · ADD 10/5 · 30席中余20席" },
        title:{ kr:"Global (Anti-)Money Laundering", en:"Global (Anti-)Money Laundering", cn:"全球反洗钱" },
        desc:{ kr:"", en:"", cn:"" } },
      { code:"OIDD 6530", meta:{ kr:"🟢 신청 가능 · SFO · 10/12–15 · Katalan · ADD 10/5 · 49석 중 26석 여유 · Audit O",
        en:"🟢 Open · SFO · Oct 12–15 · Katalan · ADD Oct 5 · 26 of 49 seats free · audit OK",
        cn:"🟢 可选 · SFO · 10/12–15 · Katalan · ADD 10/5 · 49席中余26席 · 可旁听" },
        title:{ kr:"Mathematical Modeling in Finance", en:"Mathematical Modeling and its Applications in Finance", cn:"金融数学建模" },
        desc:{ kr:"", en:"", cn:"" } },
      { code:"OIDD 6140", meta:{ kr:"🟡 대기 71명 · SFO · 11/30–12/3 · Netessine · ADD 11/23 · Audit ✕",
        en:"🟡 71 waitlisted · SFO · Nov 30 – Dec 3 · Netessine · ADD Nov 23 · no audit",
        cn:"🟡 候补71人 · SFO · 11/30–12/3 · Netessine · ADD 11/23 · 不可旁听" },
        title:{ kr:"Innovation", en:"Innovation", cn:"创新" },
        desc:{ kr:"🔥 가을 블록위크 중 대기줄이 가장 깁니다 · 👤 Netessine 은 **Senior Vice Dean for Innovation and Global Initiatives** · FAA·싱가포르 정부·Lockheed Martin·P&G·McDonald's·Rolls Royce 협업 이력 · MBA·EMBA 교육상 다수 · **Audit 이 안 되므로 정식 등록만이 유일한 길**입니다",
                en:"🔥 The longest waitlist of the fall · 👤 Netessine is **Senior Vice Dean for Innovation and Global Initiatives**, has worked with the FAA, the Government of Singapore, Lockheed Martin, P&G, McDonald's and Rolls Royce, and holds multiple teaching awards · **audit is not allowed, so a seat is the only way in**",
                cn:"🔥 秋季候补最长 · 👤 Netessine 为 **Senior Vice Dean for Innovation and Global Initiatives**,曾与 FAA、新加坡政府、Lockheed Martin、P&G、McDonald's、Rolls Royce 合作,多次获教学奖 · **不可旁听,只能正式选上**" } },
      { code:"HCMG 8600", meta:{ kr:"🟢 신청 가능 · PHL · 11/30–12/3 · Nembhard · ADD 11/23 · 78석 중 58석 여유",
        en:"🟢 Open · PHL · Nov 30 – Dec 3 · Nembhard · ADD Nov 23 · 58 of 78 seats free",
        cn:"🟢 可选 · PHL · 11/30–12/3 · Nembhard · ADD 11/23 · 78席中余58席" },
        title:{ kr:"Leading Healthcare Organizations", en:"Leading Healthcare Organizations", cn:"医疗机构领导力" },
        desc:{ kr:"자리가 넉넉해 비교적 들어가기 쉽습니다", en:"Plenty of seats, so relatively easy to get into", cn:"席位充足,较易选入" } },
      { code:"LGST 6420", meta:{ kr:"🟡 대기 42명 · SFO · 12/14–16 (3일) · Werbach · ADD 12/7 · DROP·P/F 12/15 · Audit ✕",
        en:"🟡 42 waitlisted · SFO · Dec 14–16 (3 days) · Werbach · ADD Dec 7 · DROP/PF Dec 15 · no audit",
        cn:"🟡 候补42人 · SFO · 12/14–16(3天)· Werbach · ADD 12/7 · DROP·P/F 12/15 · 不可旁听" },
        title:{ kr:"Big Data, Big Responsibilities: Toward Accountable AI", en:"Big Data, Big Responsibilities: Toward Accountable AI", cn:"大数据、大责任:迈向可问责的人工智能" },
        desc:{ kr:"🔥 이 과목으로 Aspen Institute **Ideas Worth Teaching Award(2021)** 수상 · 👤 Werbach 는 법학·기업윤리 학과장이자 **Wharton Accountable AI Lab** 총괄, Coursera 게이미피케이션 강의 수강생 50만 명 · **3일짜리로 가을 블록위크 중 가장 짧습니다**",
                en:"🔥 Won the Aspen Institute **Ideas Worth Teaching Award (2021)** for this course · 👤 Werbach chairs Legal Studies & Business Ethics, leads the **Wharton Accountable AI Lab**, and his Coursera gamification course has 500,000+ learners · **three days, the shortest block week of the fall**",
                cn:"🔥 本课获 Aspen Institute **Ideas Worth Teaching Award(2021)** · 👤 Werbach 为法学与商业伦理系主任、**Wharton Accountable AI Lab** 负责人,其 Coursera 游戏化课程学员逾50万 · **仅三天,秋季最短**" } },
      { code:"MGMT 8710 · OIDD 6540", meta:{ kr:"🔴 마감됨 · Seoul · 12/7–10 · ADD 마감 7/27 경과",
        en:"🔴 Closed · Seoul · Dec 7–10 · ADD deadline passed Jul 27",
        cn:"🔴 已截止 · 首尔 · 12/7–10 · ADD 已于 7/27 截止" },
        title:{ kr:"Advanced Global Strategy (Hernandez) · Product Management (Ulrich)", en:"Advanced Global Strategy (Hernandez) · Product Management (Ulrich)", cn:"高级全球战略(Hernandez)· 产品管理(Ulrich)" },
        desc:{ kr:"🇰🇷 **둘 다 서울 개최였는데 ADD 마감이 7월 27일로 이미 지났습니다.** 글로벌 블록위크는 항공·숙박 때문에 **반년 가까이 앞서 닫힙니다** — 내년 목록이 나오면 가장 먼저 확인하세요. OIDD 6540 은 **SFO 정규 버전(10/1–16, Ulrich, Audit O)** 이 따로 있습니다",
                en:"🇰🇷 **Both were held in Seoul, but the ADD deadline passed on Jul 27.** Global block weeks close nearly six months ahead because of travel and lodging — check next year's list the moment it appears. OIDD 6540 also runs as a **regular SFO course (Oct 1–16, Ulrich, audit allowed)**",
                cn:"🇰🇷 **两门均在首尔,ADD 已于 7月27日截止。** 全球 Block Week 因机票住宿提前近半年关闭 — 明年名单一出请第一时间查看。OIDD 6540 另有 **SFO 常规版(10/1–16,Ulrich,可旁听)**" } },
    ],
  },

  /* ── 수업 주말 일정표 ─────────────────────────────────────────────── */
  schedule: {
    notes: { kr:"⚠️ 두 섹션이 **같은 시간에 서로 다른 과목**을 듣습니다. 강의실은 과목 기준 고정 — LGST 6120 = Room 612 · FNCE 6130 = Room 615. 🏨 숙소 = Hyatt Regency SF (5 Embarcadero Ctr).",
            en:"⚠️ The two sections take **different courses at the same hour.** Rooms are fixed by course — LGST 6120 = Room 612, FNCE 6130 = Room 615. 🏨 Hotel: Hyatt Regency SF (5 Embarcadero Ctr).",
            cn:"⚠️ 两个班在**同一时段上不同课程。** 教室按课程固定 — LGST 6120 = Room 612、FNCE 6130 = Room 615。🏨 住宿:Hyatt Regency SF(5 Embarcadero Ctr)。" },
    weekends: [
      {
        start:"2026-09-11", end:"2026-09-12",
        label: { kr:"9월 11일(금)–12일(토) · SFO · ⚠️ 이번 주말은 LGST 없음 · STAT 첫 수업", en:"Fri Sep 11 – Sat Sep 12 · SFO · ⚠️ no LGST this weekend · STAT starts", cn:"9月11日(周五)–12日(周六) · SFO · ⚠️ 本周末无 LGST · STAT 首堂课" },
        days: [
          {
            label: { kr:"금요일 9/11", en:"Friday 9/11", cn:"周五 9/11" },
            rows: [
              { time:"8:30–9:30",  both:{ kr:"조식 · Dining Room", en:"Breakfast · Dining Room", cn:"早餐 · Dining Room" } },
              { time:"9:30–12:30",
                s1:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615",
                     read:{ kr:"노동시장 — ABC Ch.3.2–3.6 · Jones Ch.7", en:"Labor market — ABC Ch.3.2–3.6 · Jones Ch.7", cn:"劳动力市场 — ABC Ch.3.2–3.6 · Jones Ch.7" } },
                s2:{ kr:"STAT 6130 · Waterman · Room 612", en:"STAT 6130 · Waterman · Room 612", cn:"STAT 6130 · Waterman · Room 612",
                     read:{ kr:"⚠️ 첫 수업 시간에 **면제 시험**이 진행됩니다 · 응시하려면 사전에 Craig 과 조율 필요", en:"⚠️ the **waiver exam** runs in this first session · coordinate with Craig in advance to sit it", cn:"⚠️ 首堂课内进行**免修考试** · 应考须事先与 Craig 协调" } } },
              { time:"12:30–2:00", both:{ kr:"중식 · Dining Room", en:"Lunch · Dining Room", cn:"午餐 · Dining Room" } },
              { time:"2:00–5:00",
                s1:{ kr:"STAT 6130 · Waterman · Room 612", en:"STAT 6130 · Waterman · Room 612", cn:"STAT 6130 · Waterman · Room 612",
                     read:{ kr:"⚠️ 면제 시험은 섹션 1 은 오후 세션에 진행됩니다", en:"⚠️ for Section 1 the waiver exam runs in this afternoon session", cn:"⚠️ 第1班的免修考试在本下午场进行" } },
                s2:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615",
                     read:{ kr:"소비·저축 — ABC Ch.4.1(부록 4.A 포함) · Jones Ch.16", en:"Consumption & saving — ABC Ch.4.1 (incl. App. 4.A) · Jones Ch.16", cn:"消费与储蓄 — ABC Ch.4.1(含附录4.A)· Jones Ch.16" } } },
              { time:"5:00–6:30", both:{ kr:"석식 · Dining Room", en:"Dinner · Dining Room", cn:"晚餐 · Dining Room" } },
              { time:"5:00–11:00", both:{ kr:"🏨 Hyatt 스터디룸 개방 · Board Room A·B·C", en:"🏨 Hyatt study rooms open · Board Rooms A, B, C", cn:"🏨 Hyatt 自习室开放 · Board Room A·B·C" } },
              { time:{ kr:"종일", en:"All day", cn:"全天" }, both:{ kr:"🎓 Len Lodish 어드바이징 (예약제)", en:"🎓 Len Lodish advising (by appointment)", cn:"🎓 Len Lodish 咨询(预约制)",
                                    read:{ kr:"와튼 SF 캠퍼스 창립 부학장 · VIP 공동대표 · **이번 시즌 마지막 방문**입니다. 학업·커리어·창업 상담", en:"Founding Vice Dean of Wharton SF and co-leader of the VIP · **his last visit this season.** Academics, career and ventures", cn:"沃顿 SF 创始副院长、VIP 联合负责人 · **本季最后一次到访。** 可咨询学业、职业与创业" } } },
              { time:"8:30–11:30", both:{ kr:"🍻 Wharton Pub · Hyatt Eclipse Bar", en:"🍻 Wharton Pub · Hyatt Eclipse Bar", cn:"🍻 Wharton Pub · Hyatt Eclipse Bar" } },
            ],
          },
          {
            label: { kr:"토요일 9/12", en:"Saturday 9/12", cn:"周六 9/12" },
            rows: [
              { time:"8:00–9:00",  both:{ kr:"조식 · Dining Room", en:"Breakfast · Dining Room", cn:"早餐 · Dining Room" } },
              { time:"9:00–12:00",
                s1:{ kr:"STAT 6130 · Waterman · Room 612", en:"STAT 6130 · Waterman · Room 612", cn:"STAT 6130 · Waterman · Room 612" },
                s2:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615",
                     read:{ kr:"투자와 재화시장 균형 · ⭐ 마지막 1시간은 리뷰 세션 — Practice Midterm 배포·풀이", en:"Investment and goods market equilibrium · ⭐ the last hour is a review session with the practice midterm", cn:"投资与商品市场均衡 · ⭐ 最后一小时为复习课,发放并讲解模拟期中" } } },
              { time:"12:00–1:00", both:{ kr:"중식 · Dining Room", en:"Lunch · Dining Room", cn:"午餐 · Dining Room" } },
              { time:"1:00–4:00",
                s1:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615" },
                s2:{ kr:"STAT 6130 · Waterman · Room 612", en:"STAT 6130 · Waterman · Room 612", cn:"STAT 6130 · Waterman · Room 612" } },
            ],
          },
        ],
      },
      {
        start:"2026-08-28", end:"2026-08-29",
        label: { kr:"8월 28일(금)–29일(토) · SFO · Term 2 첫 주말 · 📸 클래스 사진 · ⚠️ LGST Quiz #1", en:"Fri Aug 28 – Sat Aug 29 · SFO · first weekend of Term 2 · 📸 class photo · ⚠️ LGST Quiz #1", cn:"8月28日(周五)–29日(周六) · SFO · 第二学期首个周末 · 📸 班级合影 · ⚠️ LGST Quiz #1" },
        days: [
          {
            label: { kr:"금요일 8/28", en:"Friday 8/28", cn:"周五 8/28" },
            rows: [
              { time:"8:30–9:30",  both:{ kr:"조식 · Dining Room", en:"Breakfast · Dining Room", cn:"早餐 · Dining Room" } },
              { time:"9:30–12:30",
                s1:{ kr:"LGST 6120 · Feinstein · Room 612", en:"LGST 6120 · Feinstein · Room 612", cn:"LGST 6120 · Feinstein · Room 612",
                     read:{ kr:"Personal Responsibility · 리딩 3편 · Values Paper 제출 마감", en:"Personal Responsibility · 3 readings · Values Paper due", cn:"Personal Responsibility · 3篇阅读 · Values Paper 截止" } },
                s2:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615" } },
              { time:"12:30–2:00", both:{ kr:"중식 · Dining Room", en:"Lunch · Dining Room", cn:"午餐 · Dining Room" } },
              { time:"12:45–1:45", both:{ kr:"📸 WEMBA 52 클래스 사진 · Dining Room", en:"📸 WEMBA 52 class photo · Dining Room", cn:"📸 WEMBA 52 班级合影 · Dining Room",
                                          read:{ kr:"비즈니스 정장 권장 · 점심시간 안에 들어 있으니 식사 순서를 조정하세요", en:"Business attire recommended · it sits inside the lunch block", cn:"建议商务着装 · 时间在午餐内" } } },
              { time:"2:00–5:00",
                s1:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615" },
                s2:{ kr:"LGST 6120 · Feinstein · Room 612", en:"LGST 6120 · Feinstein · Room 612", cn:"LGST 6120 · Feinstein · Room 612",
                     read:{ kr:"Personal Responsibility · 리딩 3편 · Values Paper 는 이 전까지 제출", en:"Personal Responsibility · 3 readings · Values Paper due before this", cn:"Personal Responsibility · 3篇阅读 · Values Paper 须在此前提交" } } },
              { time:"5:00–6:30", both:{ kr:"석식 · Dining Room", en:"Dinner · Dining Room", cn:"晚餐 · Dining Room" } },
              { time:"5:00–11:00 PM", both:{ kr:"📚 스터디룸 · Hyatt Board Rooms A·B·C", en:"📚 Study rooms · Hyatt Board Rooms A, B, C", cn:"📚 自习室 · Hyatt Board Rooms A·B·C" } },
              { time:"8:30–11:30 PM", both:{ kr:"🍺 Wharton Pub · Hyatt Eclipse Bar (자유)", en:"🍺 Wharton Pub · Hyatt Eclipse Bar (optional)", cn:"🍺 Wharton Pub · Hyatt Eclipse Bar(自由)" } },
            ],
          },
          {
            label: { kr:"토요일 8/29", en:"Saturday 8/29", cn:"周六 8/29" },
            rows: [
              { time:"8:00–9:00",  both:{ kr:"조식 · Dining Room", en:"Breakfast · Dining Room", cn:"早餐 · Dining Room" } },
              { time:"9:00–12:00",
                s1:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615" },
                s2:{ kr:"LGST 6120 · Feinstein · Room 612 · ⚠️ Quiz #1", en:"LGST 6120 · Feinstein · Room 612 · ⚠️ Quiz #1", cn:"LGST 6120 · Feinstein · Room 612 · ⚠️ Quiz #1",
                     read:{ kr:"Corporate Responsibility · 리딩 7편 · 클로즈드북 퀴즈(10%)", en:"Corporate Responsibility · 7 readings · closed-book quiz (10%)", cn:"Corporate Responsibility · 7篇阅读 · 闭卷测验(10%)" } } },
              { time:"12:00–1:00", both:{ kr:"중식 · Dining Room", en:"Lunch · Dining Room", cn:"午餐 · Dining Room" } },
              { time:"1:00–4:00",
                s1:{ kr:"LGST 6120 · Feinstein · Room 612 · ⚠️ Quiz #1", en:"LGST 6120 · Feinstein · Room 612 · ⚠️ Quiz #1", cn:"LGST 6120 · Feinstein · Room 612 · ⚠️ Quiz #1",
                     read:{ kr:"Corporate Responsibility · 리딩 7편 · 클로즈드북 퀴즈(10%)", en:"Corporate Responsibility · 7 readings · closed-book quiz (10%)", cn:"Corporate Responsibility · 7篇阅读 · 闭卷测验(10%)" } },
                s2:{ kr:"FNCE 6130 · Landry · Room 615", en:"FNCE 6130 · Landry · Room 615", cn:"FNCE 6130 · Landry · Room 615" } },
              { time:{ kr:"예약제", en:"By appt.", cn:"预约制" }, both:{ kr:"🎯 Len Lodish 어드바이징 (VIP 공동리더 · 신청은 Canvas 공지)", en:"🎯 Advising with Len Lodish (VIP co-Leader · signup via Canvas)", cn:"🎯 Len Lodish 咨询(VIP 联合负责人 · 报名见 Canvas)" } },
            ],
          },
        ],
      },
    ],
  },

  /* ── 자료 맵 준비 중 안내 (삽화 인라인) ─────────────────────────── */
  canvasSoon: {
    text: {
      kr:"✅ **가을 정규 과목 세 곳이 모두 열렸습니다** — LGST 6120 · FNCE 6130 · STAT 6130. **MKTG 6110 은 2nd Half 과목**이라 **11/6 개강과 함께** 열립니다. 지금은 신경 쓰실 것이 없어요.",
      en:"✅ **All three fall courses are now live** — LGST 6120, FNCE 6130 and STAT 6130. **MKTG 6110 is a second-half course** and opens **when it starts on Nov 6**, so there is nothing to do about it now.",
      cn:"✅ **秋季三门正课均已开放** — LGST 6120 · FNCE 6130 · STAT 6130。**MKTG 6110 属下半学期课程**,将于 **11/6 开课时**同步开放,目前无需关注。" },
  },
  canvasMap:[
    {
      subject:"LGST 6120 ✅",
      where:{ kr:"⚠️ **세 곳으로 갈립니다** — ① 리딩 = **Course Materials @ Penn Libraries** ② 리딩 = **Study.Net Materials** ③ 연습문제 핸드아웃 = **Files** · 실라버스는 **Syllabus 탭**에 docx 링크로",
              en:"⚠️ **Three places** — ① readings in **Course Materials @ Penn Libraries** ② readings in **Study.Net Materials** ③ exercise handouts in **Files** · the syllabus is a docx linked from the **Syllabus tab**",
              cn:"⚠️ **分三处** — ① 阅读在 **Course Materials @ Penn Libraries** ② 阅读在 **Study.Net Materials** ③ 练习讲义在 **Files** · 大纲为 **Syllabus 标签**中的 docx 链接" },
      submit:{ kr:"**Assignments 탭** (텍스트 입력·파일 업로드 둘 다 가능)", en:"**Assignments tab** (text entry or file upload)", cn:"**Assignments 标签**(文本或上传均可)" },
      watch:{ kr:"🔴 **교수 메일에 리딩 목록이 없습니다.** 실라버스를 직접 열어야 주말별 지정 리딩이 나옵니다 · 같은 안내가 여러 번 재발송되는데 **밑줄로 새 정보**가 표시되니 익숙해 보여도 열어보세요",
              en:"🔴 **The professor's emails do not list the readings.** You have to open the syllabus itself · the same email is re-sent as students join, with **new information underlined**, so open it even if it looks familiar",
              cn:"🔴 **教授邮件不含阅读清单**,须自行打开大纲 · 同一封邮件会多次重发,**新增内容以下划线标出**,即使看似相同也请打开" },
    },
    {
      subject:"STAT 6130 ✅",
      where:{ kr:"**Files** 에 실라버스(`Syllabus_West_2026.v1.pdf`)와 **기출 세트**(Exam 1·2·3 문제·정답·분포, example exam·정답)가 이미 올라와 있습니다",
              en:"**Files** already holds the syllabus (`Syllabus_West_2026.v1.pdf`) and a **full past-exam set** (Exams 1, 2, 3 with solutions and distributions, plus an example exam with answers)",
              cn:"**Files** 已上传大纲(`Syllabus_West_2026.v1.pdf`)与**历年试题全套**(Exam 1·2·3 试题·答案·分布,及样卷与答案)" },
      submit:{ kr:"9/11 개강 후 확인", en:"Confirm after the Sep 11 start", cn:"9/11 开课后确认" },
      watch:{ kr:"⚠️ **모든 메일 제목에 \"WEMBA WEST\" 를 넣으라**고 실라버스에 명시 · TA 는 아직 TBD",
              en:"⚠️ The syllabus asks for **\"WEMBA WEST\" in the subject line of every email** · the TA is still TBD",
              cn:"⚠️ 大纲要求**所有邮件主题含 \"WEMBA WEST\"** · 助教待定" },
    },
    {
      subject:"FNCE 6130 · MKTG 6110 ⏳",
      where:{ kr:"**8/23 기준 아직 열리지 않았습니다.** FNCE 는 8/28 개강인데도 미개설 상태예요 — 목요일 밤에 다시 확인하세요",
              en:"**Not open as of Aug 23.** FNCE starts Aug 28 and the site is still not up — check again Thursday night",
              cn:"**截至 8/23 尚未开放。** FNCE 8/28 开课但网站未上线 — 请周四晚再确认" },
      submit:{ kr:"미정", en:"TBD", cn:"待定" },
      watch:{ kr:"⚠️ **코스 사이트가 안 보인다고 등록이 안 된 게 아닙니다.** 실제 수강 목록은 Course Match ▸ Drop/Add 에서 확인",
              en:"⚠️ **A missing course site does not mean you are not registered.** Check Course Match ▸ Drop/Add for your actual enrollment",
              cn:"⚠️ **网站未显示不代表未注册。** 请在 Course Match ▸ Drop/Add 确认实际选课" },
    },
    {
      subject:"Cohort Communication",
      where:{ kr:"**Files ▸ Weekend Schedule** 에 주말 일정표 PDF · **Files ▸ Course Materials ▸ Term 5** 에 Add/Drop 안내와 Booklist",
              en:"Weekend schedule PDFs in **Files ▸ Weekend Schedule** · add/drop instructions and the booklist in **Files ▸ Course Materials ▸ Term 5**",
              cn:"周末日程 PDF 在 **Files ▸ Weekend Schedule** · 加退选说明与书单在 **Files ▸ Course Materials ▸ Term 5**" },
      submit:{ kr:"제출물 없음 (공지 전용)", en:"Nothing to submit — announcements only", cn:"无需提交(仅公告)" },
      watch:{ kr:"🔔 **가장 잘 놓치는 채널입니다.** 등록 마감·특강·워크숍·비자 공지가 전부 여기로 옵니다 · ⚠️ 가을 자료가 **'Term 5'** 로 표기돼 있는데 우리 Term 2 와 같은 것입니다",
              en:"🔔 **The easiest channel to miss.** Registration deadlines, guest sessions, workshops and visa notices all land here · ⚠️ the fall materials are labelled **'Term 5'**, which is the same as our Term 2",
              cn:"🔔 **最易漏看的频道。** 报名截止、讲座、工作坊与签证通知均在此 · ⚠️ 秋季资料标为 **'Term 5'**,与我们的第二学期相同" },
    },
    {
      subject:{ kr:"Course Match (등록·섹션)", en:"Course Match (enrollment & sections)", cn:"Course Match(选课·分班)" },
      where:{ kr:"`apps.wharton.upenn.edu/coursematch` ▸ **Drop / Add** — 실제 수강 목록, 과목별 ADD·DROP·P/F 마감, **대기 순번**이 전부 여기",
              en:"`apps.wharton.upenn.edu/coursematch` ▸ **Drop / Add** — actual enrollment, per-course ADD/DROP/PF deadlines and **your waitlist position**",
              cn:"`apps.wharton.upenn.edu/coursematch` ▸ **Drop / Add** — 实际选课、各课 ADD/DROP/PF 截止与**候补顺位**" },
      submit:{ kr:"섹션 확인은 **Wharton Reports ▸ My Class Lists** — 과목 코드 끝자리가 섹션 번호", en:"Section check: **Wharton Reports ▸ My Class Lists** — last digit of the course code", cn:"分班查询:**Wharton Reports ▸ My Class Lists** — 课程代码末位" },
      watch:{ kr:"⭐ 각 과목 설명줄에 **ADD·DROP·P/F 마감이 개별로** 적혀 있습니다. 시스템 종료일(12/19)과 헷갈리지 마세요",
              en:"⭐ Each course line carries **its own ADD, DROP and P/F dates**. Do not confuse them with the system close date of Dec 19",
              cn:"⭐ 每门课的说明行标注**各自的 ADD·DROP·P/F 截止**,勿与系统关闭日(12/19)混淆" },
    },
  ],

  /* ── 소셜 ─────────────────────────────────────────────────────────── */
  social: {
    url: "https://wemba52sfsocial.netlify.app/",
    embedUrl: "https://wemba52sfsocial.netlify.app/#dinners",
    embed: false,
    desc: {
      kr:"금요일 디너는 동네·Afters 를 함께 정하고 그룹(최대 8명)별로 식당을 골라요. 그룹에 참여하거나 직접 만들 수 있고, 팀 캡틴이 예약을 맡습니다. (목요일 도착·토요일 수업 후 모임도)",
      en:"For Friday dinner, pick a shared neighborhood/Afters, then each group (max 8) chooses its restaurant. Join a group or start your own; a team captain books it. (Thursday arrivals & Saturday after-class too.)",
      cn:"周五聚餐先共同选定街区·Afters,各组(最多8人)自选餐厅。可加入或自建小组,由队长负责预订。(也有周四抵达与周六课后活动。)",
    },
    cta: { kr:"디너 약속 정하러 가기", en:"Open the dinner planner", cn:"去安排聚餐" },
  },
};
